import type { PlayerState } from './gameStore';

export type AchievementType = 'streak' | 'habit' | 'mission' | 'level' | 'discipline' | 'special';

export interface AchievementDef {
  id: string;
  type: AchievementType;
  label: string;
  value: number;
  rank: string;
  icon: string;
  description: string;
  requirements: string[];
  check: (state: PlayerState) => boolean;
  progress: (state: PlayerState) => { current: number; target: number };
}

export interface UnlockedAchievement {
  id: string;
  unlockedAt: string;
}

const RANK_COLORS: Record<string, { bg: string; border: string; glow: string; text: string }> = {
  E: { bg: 'from-gray-700 to-gray-800', border: 'border-gray-500', glow: '', text: 'text-gray-300' },
  D: { bg: 'from-blue-800 to-blue-900', border: 'border-blue-500', glow: 'shadow-blue-500/30', text: 'text-blue-300' },
  C: { bg: 'from-emerald-800 to-emerald-900', border: 'border-emerald-500', glow: 'shadow-emerald-500/30', text: 'text-emerald-300' },
  B: { bg: 'from-purple-800 to-purple-900', border: 'border-purple-500', glow: 'shadow-purple-500/30', text: 'text-purple-300' },
  A: { bg: 'from-red-800 to-red-900', border: 'border-red-500', glow: 'shadow-red-500/30', text: 'text-red-300' },
  S: { bg: 'from-yellow-700 to-amber-800', border: 'border-yellow-400', glow: 'shadow-yellow-400/40', text: 'text-yellow-300' },
  Monarca: { bg: 'from-gray-900 to-black', border: 'border-purple-400', glow: 'shadow-purple-500/50', text: 'text-purple-300' },
};

export function getRankStyle(rank: string) {
  return RANK_COLORS[rank] || RANK_COLORS.E;
}

// Helper for completed missions count
const completedMissions = (s: PlayerState) => s.missions.filter(m => m.status === 'Concluída').length;
const hardMissions = (s: PlayerState) => s.missions.filter(m => m.status === 'Concluída' && m.difficulty === 'Difícil').length;
const maxHabitDone = (s: PlayerState) => Math.max(0, ...s.habits.map(h => Object.values(h.history).filter(v => v === 'done').length));
const protocolsDone = (s: PlayerState) => s.failureProtocols.filter(fp => fp.status === 'Concluído').length;
const RANKS_ORDER = ['E', 'D', 'C', 'B', 'A', 'S', 'Monarca'];
const rankIdx = (r: string) => RANKS_ORDER.indexOf(r);

export const ACHIEVEMENTS: AchievementDef[] = [
  // ========== STREAK ==========
  { id: 'streak-3', type: 'streak', label: '3 Dias de Consistência', value: 3, rank: 'E', icon: '🔥',
    description: 'Mantenha uma sequência de 3 dias fazendo check-in.',
    requirements: ['Fazer check-in diário por 3 dias seguidos'],
    check: s => s.streak >= 3, progress: s => ({ current: Math.min(s.streak, 3), target: 3 }) },
  { id: 'streak-7', type: 'streak', label: '7 Dias de Disciplina', value: 7, rank: 'D', icon: '🔥',
    description: 'Uma semana inteira sem parar. Disciplina de verdade.',
    requirements: ['Manter streak de 7 dias consecutivos'],
    check: s => s.streak >= 7, progress: s => ({ current: Math.min(s.streak, 7), target: 7 }) },
  { id: 'streak-15', type: 'streak', label: '15 Dias Imparável', value: 15, rank: 'C', icon: '🔥',
    description: 'Duas semanas de consistência. Você é imparável.',
    requirements: ['Manter streak de 15 dias consecutivos'],
    check: s => s.streak >= 15, progress: s => ({ current: Math.min(s.streak, 15), target: 15 }) },
  { id: 'streak-30', type: 'streak', label: '30 Dias de Aço', value: 30, rank: 'B', icon: '🔥',
    description: 'Um mês inteiro. Sua disciplina é de aço.',
    requirements: ['Manter streak de 30 dias consecutivos'],
    check: s => s.streak >= 30, progress: s => ({ current: Math.min(s.streak, 30), target: 30 }) },
  { id: 'streak-60', type: 'streak', label: '60 Dias Lendário', value: 60, rank: 'A', icon: '🔥',
    description: 'Dois meses sem parar. Poucos chegam aqui.',
    requirements: ['Manter streak de 60 dias consecutivos'],
    check: s => s.streak >= 60, progress: s => ({ current: Math.min(s.streak, 60), target: 60 }) },
  { id: 'streak-100', type: 'streak', label: '100 Dias — Monarca', value: 100, rank: 'S', icon: '🔥',
    description: 'Cem dias de pura determinação. Você é um monarca.',
    requirements: ['Manter streak de 100 dias consecutivos'],
    check: s => s.streak >= 100, progress: s => ({ current: Math.min(s.streak, 100), target: 100 }) },
  { id: 'streak-200', type: 'streak', label: '200 Dias — Imortal', value: 200, rank: 'Monarca', icon: '🔥',
    description: 'Duzentos dias. A consistência virou instinto.',
    requirements: ['Manter streak de 200 dias consecutivos'],
    check: s => s.streak >= 200, progress: s => ({ current: Math.min(s.streak, 200), target: 200 }) },
  { id: 'streak-365', type: 'streak', label: '365 Dias — Lenda Eterna', value: 365, rank: 'Monarca', icon: '🔥',
    description: 'Um ano inteiro. Você transcendeu o humano.',
    requirements: ['Manter streak de 365 dias consecutivos'],
    check: s => s.streak >= 365, progress: s => ({ current: Math.min(s.streak, 365), target: 365 }) },

  // ========== MISSIONS ==========
  { id: 'mission-first', type: 'mission', label: 'Primeira Vitória', value: 1, rank: 'E', icon: '⚔️',
    description: 'Complete sua primeira missão. Toda jornada começa com um passo.',
    requirements: ['Concluir 1 missão de qualquer tipo'],
    check: s => completedMissions(s) >= 1, progress: s => ({ current: Math.min(completedMissions(s), 1), target: 1 }) },
  { id: 'mission-5', type: 'mission', label: '5 Missões Concluídas', value: 5, rank: 'D', icon: '⚔️',
    description: 'Cinco missões completas. O ritmo está se formando.',
    requirements: ['Concluir 5 missões no total'],
    check: s => completedMissions(s) >= 5, progress: s => ({ current: Math.min(completedMissions(s), 5), target: 5 }) },
  { id: 'mission-10', type: 'mission', label: '10 Missões Concluídas', value: 10, rank: 'C', icon: '⚔️',
    description: 'Dez vitórias acumuladas. Guerreiro em ascensão.',
    requirements: ['Concluir 10 missões no total'],
    check: s => completedMissions(s) >= 10, progress: s => ({ current: Math.min(completedMissions(s), 10), target: 10 }) },
  { id: 'mission-25', type: 'mission', label: '25 Missões Concluídas', value: 25, rank: 'B', icon: '⚔️',
    description: 'Vinte e cinco missões. Disciplina operacional.',
    requirements: ['Concluir 25 missões no total'],
    check: s => completedMissions(s) >= 25, progress: s => ({ current: Math.min(completedMissions(s), 25), target: 25 }) },
  { id: 'mission-50', type: 'mission', label: '50 Missões Concluídas', value: 50, rank: 'A', icon: '⚔️',
    description: 'Cinquenta missões. Você é uma máquina de execução.',
    requirements: ['Concluir 50 missões no total'],
    check: s => completedMissions(s) >= 50, progress: s => ({ current: Math.min(completedMissions(s), 50), target: 50 }) },
  { id: 'mission-100', type: 'mission', label: '100 Missões — Veterano', value: 100, rank: 'S', icon: '⚔️',
    description: 'Cem missões. Veterano de guerra da produtividade.',
    requirements: ['Concluir 100 missões no total'],
    check: s => completedMissions(s) >= 100, progress: s => ({ current: Math.min(completedMissions(s), 100), target: 100 }) },
  { id: 'mission-hard', type: 'mission', label: 'Missão Difícil Concluída', value: 1, rank: 'C', icon: '⚔️',
    description: 'Enfrentou o desafio e venceu. Coragem pura.',
    requirements: ['Concluir 1 missão com dificuldade "Difícil"'],
    check: s => hardMissions(s) >= 1, progress: s => ({ current: Math.min(hardMissions(s), 1), target: 1 }) },
  { id: 'mission-hard-5', type: 'mission', label: '5 Missões Difíceis', value: 5, rank: 'A', icon: '⚔️',
    description: 'Cinco missões difíceis. Você busca o impossível.',
    requirements: ['Concluir 5 missões com dificuldade "Difícil"'],
    check: s => hardMissions(s) >= 5, progress: s => ({ current: Math.min(hardMissions(s), 5), target: 5 }) },
  { id: 'mission-hard-10', type: 'mission', label: '10 Missões Difíceis — Caçador de Elite', value: 10, rank: 'S', icon: '⚔️',
    description: 'Dez missões difíceis concluídas. Caçador de elite.',
    requirements: ['Concluir 10 missões com dificuldade "Difícil"'],
    check: s => hardMissions(s) >= 10, progress: s => ({ current: Math.min(hardMissions(s), 10), target: 10 }) },

  // ========== HABITS ==========
  { id: 'habit-first', type: 'habit', label: 'Primeiro Hábito Criado', value: 1, rank: 'E', icon: '🧠',
    description: 'Criou seu primeiro hábito. A fundação começa aqui.',
    requirements: ['Criar 1 hábito'],
    check: s => s.habits.length >= 1, progress: s => ({ current: Math.min(s.habits.length, 1), target: 1 }) },
  { id: 'habit-3', type: 'habit', label: '3 Hábitos Ativos', value: 3, rank: 'D', icon: '🧠',
    description: 'Três hábitos ativos. Sua rotina está se formando.',
    requirements: ['Ter 3 hábitos criados simultaneamente'],
    check: s => s.habits.length >= 3, progress: s => ({ current: Math.min(s.habits.length, 3), target: 3 }) },
  { id: 'habit-5', type: 'habit', label: '5 Hábitos Ativos', value: 5, rank: 'C', icon: '🧠',
    description: 'Cinco hábitos. Uma rotina de elite.',
    requirements: ['Ter 5 hábitos criados simultaneamente'],
    check: s => s.habits.length >= 5, progress: s => ({ current: Math.min(s.habits.length, 5), target: 5 }) },
  { id: 'habit-done-5', type: 'habit', label: '5 Dias de Hábito', value: 5, rank: 'E', icon: '🧠',
    description: 'Cinco dias de um hábito cumprido. O começo da consistência.',
    requirements: ['Completar 1 hábito por 5 dias (total)'],
    check: s => maxHabitDone(s) >= 5, progress: s => ({ current: Math.min(maxHabitDone(s), 5), target: 5 }) },
  { id: 'habit-done-10', type: 'habit', label: '10 Dias de Hábito', value: 10, rank: 'D', icon: '🧠',
    description: 'Criou seu primeiro hábito. A fundação começa aqui.',
    requirements: ['Criar 1 hábito'],
    check: s => s.habits.length >= 1, progress: s => ({ current: Math.min(s.habits.length, 1), target: 1 }) },
  { id: 'habit-3', type: 'habit', label: '3 Hábitos Ativos', value: 3, rank: 'D', icon: '🧠',
    description: 'Três hábitos ativos. Sua rotina está se formando.',
    requirements: ['Ter 3 hábitos criados simultaneamente'],
    check: s => s.habits.length >= 3, progress: s => ({ current: Math.min(s.habits.length, 3), target: 3 }) },
  { id: 'habit-5', type: 'habit', label: '5 Hábitos Ativos', value: 5, rank: 'C', icon: '🧠',
    description: 'Cinco hábitos. Uma rotina de elite.',
    requirements: ['Ter 5 hábitos criados simultaneamente'],
    check: s => s.habits.length >= 5, progress: s => ({ current: Math.min(s.habits.length, 5), target: 5 }) },
  { id: 'habit-done-10', type: 'habit', label: '10 Dias de Hábito', value: 10, rank: 'D', icon: '🧠',
    description: 'Dez dias de um hábito cumprido. Persistência.',
    requirements: ['Completar 1 hábito por 10 dias (total)'],
    check: s => maxHabitDone(s) >= 10, progress: s => ({ current: Math.min(maxHabitDone(s), 10), target: 10 }) },
  { id: 'habit-done-15', type: 'habit', label: '15 Dias de Hábito', value: 15, rank: 'D', icon: '🧠',
    description: 'Quinze dias de consistência. O hábito está criando raízes.',
    requirements: ['Completar 1 hábito por 15 dias (total)'],
    check: s => maxHabitDone(s) >= 15, progress: s => ({ current: Math.min(maxHabitDone(s), 15), target: 15 }) },
  { id: 'habit-done-20', type: 'habit', label: '20 Dias de Hábito', value: 20, rank: 'C', icon: '🧠',
    description: 'Vinte dias. A neurociência diz que o hábito está se formando.',
    requirements: ['Completar 1 hábito por 20 dias (total)'],
    check: s => maxHabitDone(s) >= 20, progress: s => ({ current: Math.min(maxHabitDone(s), 20), target: 20 }) },
  { id: 'habit-done-25', type: 'habit', label: '25 Dias de Hábito', value: 25, rank: 'C', icon: '🧠',
    description: 'Vinte e cinco dias. Quase um mês inteiro de disciplina.',
    requirements: ['Completar 1 hábito por 25 dias (total)'],
    check: s => maxHabitDone(s) >= 25, progress: s => ({ current: Math.min(maxHabitDone(s), 25), target: 25 }) },
  { id: 'habit-done-30', type: 'habit', label: '30 Dias de Hábito', value: 30, rank: 'C', icon: '🧠',
    description: 'Um mês de hábito. Isso já é parte de você.',
    requirements: ['Completar 1 hábito por 30 dias (total)'],
    check: s => maxHabitDone(s) >= 30, progress: s => ({ current: Math.min(maxHabitDone(s), 30), target: 30 }) },
  { id: 'habit-done-60', type: 'habit', label: '60 Dias de Hábito', value: 60, rank: 'B', icon: '🧠',
    description: 'Sessenta dias. O hábito virou identidade.',
    requirements: ['Completar 1 hábito por 60 dias (total)'],
    check: s => maxHabitDone(s) >= 60, progress: s => ({ current: Math.min(maxHabitDone(s), 60), target: 60 }) },
  { id: 'habit-done-100', type: 'habit', label: '100 Dias — Mestre do Hábito', value: 100, rank: 'A', icon: '🧠',
    description: 'Cem dias de consistência em um hábito. Mestre.',
    requirements: ['Completar 1 hábito por 100 dias (total)'],
    check: s => maxHabitDone(s) >= 100, progress: s => ({ current: Math.min(maxHabitDone(s), 100), target: 100 }) },
  { id: 'habit-done-200', type: 'habit', label: '200 Dias — Monge do Hábito', value: 200, rank: 'S', icon: '🧠',
    description: 'Duzentos dias. A disciplina transcende.',
    requirements: ['Completar 1 hábito por 200 dias (total)'],
    check: s => maxHabitDone(s) >= 200, progress: s => ({ current: Math.min(maxHabitDone(s), 200), target: 200 }) },

  // ========== LEVEL / RANK ==========
  { id: 'level-e3', type: 'level', label: 'Primeiros Passos', value: 3, rank: 'E', icon: '📈',
    description: 'Alcance o Nível 3 no Rank E. Você está começando a evoluir.',
    requirements: ['Alcançar Nível 3 no Rank E'],
    check: s => (s.rank === 'E' && s.level >= 3) || rankIdx(s.rank) > 0, progress: s => ({ current: rankIdx(s.rank) > 0 ? 3 : Math.min(s.level, 3), target: 3 }) },
  { id: 'level-e5', type: 'level', label: 'Pronto para Ascender', value: 5, rank: 'E', icon: '📈',
    description: 'Nível 5 no Rank E. Você está pronto para o próximo patamar.',
    requirements: ['Alcançar Nível 5 no Rank E (subir para Rank D)'],
    check: s => rankIdx(s.rank) >= 1, progress: s => ({ current: rankIdx(s.rank) >= 1 ? 5 : Math.min(s.level, 5), target: 5 }) },
  { id: 'rank-D', type: 'level', label: 'Rank D Alcançado', value: 0, rank: 'D', icon: '📈',
    description: 'Ascendeu ao Rank D. A jornada real começa.',
    requirements: ['Alcançar o Rank D'],
    check: s => rankIdx(s.rank) >= 1, progress: s => ({ current: rankIdx(s.rank) >= 1 ? 1 : 0, target: 1 }) },
  { id: 'rank-C', type: 'level', label: 'Rank C Alcançado', value: 0, rank: 'C', icon: '📈',
    description: 'Rank C. Domínio inicial conquistado.',
    requirements: ['Alcançar o Rank C'],
    check: s => rankIdx(s.rank) >= 2, progress: s => ({ current: rankIdx(s.rank) >= 2 ? 1 : 0, target: 1 }) },
  { id: 'rank-B', type: 'level', label: 'Rank B Alcançado', value: 0, rank: 'B', icon: '📈',
    description: 'Rank B. Força interior desbloqueada.',
    requirements: ['Alcançar o Rank B'],
    check: s => rankIdx(s.rank) >= 3, progress: s => ({ current: rankIdx(s.rank) >= 3 ? 1 : 0, target: 1 }) },
  { id: 'level-b3', type: 'level', label: 'Elite em Formação', value: 3, rank: 'B', icon: '📈',
    description: 'Nível 3 no Rank B. Elite em formação.',
    requirements: ['Alcançar Nível 3 no Rank B'],
    check: s => (s.rank === 'B' && s.level >= 3) || rankIdx(s.rank) > 3, progress: s => ({ current: rankIdx(s.rank) > 3 ? 3 : s.rank === 'B' ? Math.min(s.level, 3) : 0, target: 3 }) },
  { id: 'rank-A', type: 'level', label: 'Rank A Alcançado', value: 0, rank: 'A', icon: '📈',
    description: 'Rank A. Presença dominante.',
    requirements: ['Alcançar o Rank A'],
    check: s => rankIdx(s.rank) >= 4, progress: s => ({ current: rankIdx(s.rank) >= 4 ? 1 : 0, target: 1 }) },
  { id: 'rank-S', type: 'level', label: 'Rank S Alcançado', value: 0, rank: 'S', icon: '📈',
    description: 'Rank S. Além do comum. Pouquíssimos chegam aqui.',
    requirements: ['Alcançar o Rank S'],
    check: s => rankIdx(s.rank) >= 5, progress: s => ({ current: rankIdx(s.rank) >= 5 ? 1 : 0, target: 1 }) },
  { id: 'level-s5', type: 'level', label: 'Quase Lendário', value: 5, rank: 'S', icon: '📈',
    description: 'Nível 5 no Rank S. À beira da lenda.',
    requirements: ['Alcançar Nível 5 no Rank S'],
    check: s => (s.rank === 'S' && s.level >= 5) || s.rank === 'Monarca', progress: s => ({ current: s.rank === 'Monarca' ? 5 : s.rank === 'S' ? Math.min(s.level, 5) : 0, target: 5 }) },
  { id: 'rank-Monarca', type: 'level', label: 'Monarca Ascendido', value: 0, rank: 'Monarca', icon: '👑',
    description: 'O rank supremo. Você ascendeu.',
    requirements: ['Alcançar o Rank Monarca'],
    check: s => s.rank === 'Monarca', progress: s => ({ current: s.rank === 'Monarca' ? 1 : 0, target: 1 }) },
  { id: 'level-m5', type: 'level', label: 'Forma Final', value: 5, rank: 'Monarca', icon: '👑',
    description: 'Nível 5 no Rank Monarca. Forma Final alcançada.',
    requirements: ['Alcançar Nível 5 no Rank Monarca'],
    check: s => s.rank === 'Monarca' && s.level >= 5, progress: s => ({ current: s.rank === 'Monarca' ? Math.min(s.level, 5) : 0, target: 5 }) },

  // ========== DISCIPLINE ==========
  { id: 'protocol-done', type: 'discipline', label: 'Protocolo Concluído', value: 1, rank: 'D', icon: '💀',
    description: 'Completou um protocolo de falha. Redenção.',
    requirements: ['Concluir 1 Protocolo de Falha dentro do prazo'],
    check: s => protocolsDone(s) >= 1, progress: s => ({ current: Math.min(protocolsDone(s), 1), target: 1 }) },
  { id: 'protocol-3', type: 'discipline', label: '3 Protocolos Concluídos', value: 3, rank: 'B', icon: '💀',
    description: 'Três protocolos concluídos. Resiliência comprovada.',
    requirements: ['Concluir 3 Protocolos de Falha'],
    check: s => protocolsDone(s) >= 3, progress: s => ({ current: Math.min(protocolsDone(s), 3), target: 3 }) },
  { id: 'protocol-10', type: 'discipline', label: '10 Protocolos — Indestrutível', value: 10, rank: 'A', icon: '💀',
    description: 'Dez protocolos. Nada te derruba.',
    requirements: ['Concluir 10 Protocolos de Falha'],
    check: s => protocolsDone(s) >= 10, progress: s => ({ current: Math.min(protocolsDone(s), 10), target: 10 }) },
  { id: 'no-fail-7', type: 'discipline', label: '7 Dias Sem Falhar', value: 7, rank: 'C', icon: '💀',
    description: 'Sete dias perfeitos. Zero falhas.',
    requirements: ['Manter streak de 7 dias', 'Nenhum dia perdido'],
    check: s => s.streak >= 7 && s.missedDays === 0, progress: s => ({ current: Math.min(s.streak, 7), target: 7 }) },
  { id: 'no-fail-30', type: 'discipline', label: '30 Dias Sem Falhar', value: 30, rank: 'A', icon: '💀',
    description: 'Trinta dias impecáveis. Perfeição.',
    requirements: ['Manter streak de 30 dias', 'Nenhum dia perdido'],
    check: s => s.streak >= 30 && s.missedDays === 0, progress: s => ({ current: Math.min(s.streak, 30), target: 30 }) },

  // ========== SPECIAL ==========
  { id: 'awakening', type: 'special', label: 'Despertar Completo', value: 0, rank: 'E', icon: '👑',
    description: 'Preencheu todos os campos do Despertar. Você sabe quem quer se tornar.',
    requirements: ['Preencher "O que quero me tornar"', 'Preencher "O que rejeito"', 'Preencher "Minha dor"'],
    check: s => !!(s.awakening.become && s.awakening.reject && s.awakening.pain),
    progress: s => ({ current: [s.awakening.become, s.awakening.reject, s.awakening.pain].filter(Boolean).length, target: 3 }) },
  { id: 'journal-1', type: 'special', label: 'Primeira Reflexão', value: 1, rank: 'E', icon: '📝',
    description: 'Escreveu sua primeira entrada no diário.',
    requirements: ['Criar 1 entrada no diário'],
    check: s => s.journal.length >= 1, progress: s => ({ current: Math.min(s.journal.length, 1), target: 1 }) },
  { id: 'journal-5', type: 'special', label: '5 Entradas no Diário', value: 5, rank: 'D', icon: '📝',
    description: 'Cinco reflexões. Autoconhecimento em ação.',
    requirements: ['Criar 5 entradas no diário'],
    check: s => s.journal.length >= 5, progress: s => ({ current: Math.min(s.journal.length, 5), target: 5 }) },
  { id: 'journal-20', type: 'special', label: '20 Entradas no Diário', value: 20, rank: 'C', icon: '📝',
    description: 'Vinte reflexões. Mentalidade em evolução.',
    requirements: ['Criar 20 entradas no diário'],
    check: s => s.journal.length >= 20, progress: s => ({ current: Math.min(s.journal.length, 20), target: 20 }) },
  { id: 'journal-50', type: 'special', label: '50 Entradas — Escritor', value: 50, rank: 'B', icon: '📝',
    description: 'Cinquenta entradas. A escrita te transformou.',
    requirements: ['Criar 50 entradas no diário'],
    check: s => s.journal.length >= 50, progress: s => ({ current: Math.min(s.journal.length, 50), target: 50 }) },
  { id: 'journal-100', type: 'special', label: '100 Entradas — Filósofo', value: 100, rank: 'A', icon: '📝',
    description: 'Cem entradas. Mestre do autoconhecimento.',
    requirements: ['Criar 100 entradas no diário'],
    check: s => s.journal.length >= 100, progress: s => ({ current: Math.min(s.journal.length, 100), target: 100 }) },
  { id: 'gold-100', type: 'special', label: '100 Gold', value: 100, rank: 'E', icon: '💰',
    description: 'Acumulou 100 de ouro. O tesouro cresce.',
    requirements: ['Acumular 100 Gold'],
    check: s => s.gold >= 100, progress: s => ({ current: Math.min(s.gold, 100), target: 100 }) },
  { id: 'gold-500', type: 'special', label: '500 Gold', value: 500, rank: 'C', icon: '💰',
    description: 'Quinhentas moedas. Riqueza em construção.',
    requirements: ['Acumular 500 Gold'],
    check: s => s.gold >= 500, progress: s => ({ current: Math.min(s.gold, 500), target: 500 }) },
  { id: 'gold-2000', type: 'special', label: '2000 Gold — Ricaço', value: 2000, rank: 'A', icon: '💰',
    description: 'Duas mil moedas. Ricaço da produtividade.',
    requirements: ['Acumular 2000 Gold'],
    check: s => s.gold >= 2000, progress: s => ({ current: Math.min(s.gold, 2000), target: 2000 }) },
  { id: 'gold-5000', type: 'special', label: '5000 Gold — Tesouro Vivo', value: 5000, rank: 'S', icon: '💰',
    description: 'Cinco mil moedas. Lendário.',
    requirements: ['Acumular 5000 Gold'],
    check: s => s.gold >= 5000, progress: s => ({ current: Math.min(s.gold, 5000), target: 5000 }) },
  { id: 'challenge-1', type: 'special', label: 'Primeiro Desafio Criado', value: 1, rank: 'E', icon: '🎯',
    description: 'Criou seu primeiro desafio. Determinação.',
    requirements: ['Criar 1 desafio'],
    check: s => s.challenges.length >= 1, progress: s => ({ current: Math.min(s.challenges.length, 1), target: 1 }) },
  { id: 'reward-1', type: 'special', label: 'Primeira Recompensa Resgatada', value: 1, rank: 'E', icon: '🎁',
    description: 'Resgatou sua primeira recompensa. Merecido!',
    requirements: ['Resgatar 1 recompensa na loja'],
    check: s => s.rewards.filter(r => r.redeemed).length >= 1, progress: s => ({ current: Math.min(s.rewards.filter(r => r.redeemed).length, 1), target: 1 }) },
  { id: 'reward-5', type: 'special', label: '5 Recompensas Resgatadas', value: 5, rank: 'C', icon: '🎁',
    description: 'Cinco recompensas. Colhendo os frutos.',
    requirements: ['Resgatar 5 recompensas na loja'],
    check: s => s.rewards.filter(r => r.redeemed).length >= 5, progress: s => ({ current: Math.min(s.rewards.filter(r => r.redeemed).length, 5), target: 5 }) },
];

export function checkNewAchievements(state: PlayerState, unlocked: UnlockedAchievement[]): AchievementDef[] {
  const unlockedIds = new Set(unlocked.map(u => u.id));
  return ACHIEVEMENTS.filter(a => !unlockedIds.has(a.id) && a.check(state));
}
