import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Droplets, Trash2, Clock3, RotateCcw, Save, Shield, Database } from "lucide-react";
import { deleteUserState, deleteUserStatesByPrefix } from "@/lib/userState";

type Props = { uid: string; nome: string; busy: boolean; setBusy: (v: boolean) => void };
type Config = { agua_meta_ml: number | null; jejum_reset_at: string | null; agua_reset_at: string | null };

export default function AdminWaterTools({ uid, nome, busy, setBusy }: Props) {
  const qc = useQueryClient(); const [meta, setMeta] = useState(""); const [preparing, setPreparing] = useState(false);
  const prepararBanco = async () => { setPreparing(true); try { const { data: result, error } = await supabase.rpc("admin_preparar_agua_jejum"); if (error) throw error; toast.success(result?.message ?? "Banco de água e jejum preparado com sucesso."); await qc.invalidateQueries({ queryKey: ["admin-water-jejum-config", uid] }); } catch (e: any) { toast.error(`Não foi possível preparar o banco: ${e.message}`); } finally { setPreparing(false); } };
  const garantirEstrutura = async () => { const { error } = await supabase.rpc("admin_preparar_agua_jejum"); if (error) throw error; };
  const { data } = useQuery({ queryKey: ["admin-water-jejum-config", uid], queryFn: async () => { try { await garantirEstrutura(); } catch {} const { data, error } = await (supabase as any).from("users").select("agua_meta_ml, jejum_reset_at, agua_reset_at").eq("id", uid).single(); if (error) throw error; return data as Config; }, enabled: !!uid, retry: false });
  useEffect(() => { if (data?.agua_meta_ml != null) setMeta(String(data.agua_meta_ml)); else if (data) setMeta(""); }, [data?.agua_meta_ml, data]);
  const saveMeta = async () => { const value = Number(meta); if (!Number.isInteger(value) || value <= 0 || value > 1000000) { toast.error("Informe uma meta inteira entre 1 e 1.000.000 ml."); return; } setBusy(true); try { await garantirEstrutura(); const { error } = await (supabase as any).from("users").update({ agua_meta_ml: value }).eq("id", uid); if (error) throw error; toast.success(`Meta de água de ${value} ml salva para ${nome}`); await qc.invalidateQueries({ queryKey: ["admin-water-jejum-config", uid] }); } catch (e: any) { toast.error(`Não foi possível salvar a meta: ${e.message}`); } finally { setBusy(false); } };
  const resetJejum = async () => { if (!confirm(`Apagar TODO o histórico de jejum de ${nome}? Isso também apagará o maior jejum, o estado ativo e as conquistas de jejum.`)) return; setBusy(true); try { await garantirEstrutura(); const now = new Date().toISOString(); const { error: userError } = await (supabase as any).from("users").update({ jejum_reset_at: now }).eq("id", uid); if (userError) throw userError; await Promise.all([deleteUserState(uid, "jejum_sessoes"), deleteUserState(uid, "jejum_ativo"), deleteUserStatesByPrefix(uid, "agua_dia:")]); const { error: achievementError } = await supabase.from("conquistas").delete().eq("user_id", uid).like("tipo", "jejum_%"); if (achievementError) throw achievementError; toast.success("Histórico, maior jejum, jejum ativo e conquistas de jejum apagados."); await qc.invalidateQueries({ queryKey: ["admin-water-jejum-config", uid] }); await qc.invalidateQueries({ queryKey: ["admin-conq", uid] }); } catch (e: any) { toast.error(`Não foi possível apagar o jejum: ${e.message}`); } finally { setBusy(false); } };
  const resetAgua = async () => { if (!confirm(`Zerar os registros de água de ${nome}?`)) return; setBusy(true); try { await garantirEstrutura(); await deleteUserStatesByPrefix(uid, "agua_dia:"); const { error } = await (supabase as any).from("users").update({ agua_reset_at: new Date().toISOString() }).eq("id", uid); if (error) throw error; toast.success("Histórico de água zerado no banco de dados."); await qc.invalidateQueries({ queryKey: ["admin-water-jejum-config", uid] }); } catch (e: any) { toast.error(`Não foi possível zerar a água: ${e.message}`); } finally { setBusy(false); } };
  return <div className="space-y-3"><div className="rpg-panel p-4 space-y-3 border-primary/30"><p className="text-[10px] uppercase tracking-[0.3em] text-primary flex items-center gap-1"><Database className="w-3 h-3" /> BANCO — ÁGUA E JEJUM</p><p className="text-xs text-muted-foreground">Prepara automaticamente as colunas necessárias. O histórico persistente agora fica na conta, não somente neste dispositivo.</p><button onClick={prepararBanco} disabled={busy || preparing} className="w-full btn-pixel py-2.5 rounded-md text-xs flex items-center justify-center gap-2"><Database className="w-4 h-4" /> {preparing ? "Preparando banco..." : "Preparar / Corrigir Banco"}</button></div><div className="rpg-panel p-4 space-y-3"><p className="text-[10px] uppercase tracking-[0.3em] text-primary flex items-center gap-1"><Droplets className="w-3 h-3" /> ÁGUA — CONFIGURAÇÃO INDIVIDUAL</p><p className="text-xs text-muted-foreground">A meta é definida manualmente para este usuário.</p><div className="flex gap-2"><input type="number" min="1" max="1000000" step="1" value={meta} onChange={e => setMeta(e.target.value)} className="flex-1 bg-secondary border border-border rounded-md px-3 py-2 text-sm" placeholder="Ex.: 5000" /><button onClick={saveMeta} disabled={busy} className="btn-pixel px-4 rounded-md text-xs flex items-center gap-2"><Save className="w-4 h-4" /> Salvar ml</button></div><p className="text-[9px] text-muted-foreground">Meta atual: <strong className="text-cyan-300">{data?.agua_meta_ml ?? "—"} ml</strong></p></div><div className="rpg-panel p-4 space-y-2"><p className="text-[10px] uppercase tracking-[0.25em] text-muted-foreground">LIMPEZA DO RASTREADOR</p><button onClick={resetAgua} disabled={busy} className="w-full border border-destructive/40 text-destructive hover:bg-destructive/10 py-2.5 rounded-md text-xs flex items-center justify-center gap-2"><RotateCcw className="w-4 h-4" /> Zerar histórico de água</button></div><div className="rpg-panel p-4 space-y-2 border-amber-400/20"><p className="text-[10px] uppercase tracking-[0.25em] text-amber-300 flex items-center gap-1"><Clock3 className="w-3 h-3" /> JEJUM</p><p className="text-xs text-muted-foreground">Remove histórico, maior tempo, estado ativo e conquistas de jejum diretamente da persistência da conta.</p><button onClick={resetJejum} disabled={busy} className="w-full border border-destructive/50 text-destructive hover:bg-destructive/10 py-2.5 rounded-md text-xs flex items-center justify-center gap-2"><Trash2 className="w-4 h-4" /> Apagar histórico de jejum</button></div><div className="rpg-panel p-4 space-y-2 border-destructive/30"><p className="text-[10px] uppercase tracking-[0.25em] text-destructive flex items-center gap-1"><Shield className="w-3 h-3" /> RESET TOTAL</p><p className="text-xs text-muted-foreground">Os resets administrativos limpam também o estado persistente do rastreador, não apenas o cache do navegador.</p></div></div>;
}
