import { useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useQuery } from "@tanstack/react-query";
import { useAuth } from "@/hooks/useAuth";
import Shell from "@/components/Shell";
import { fetchConquistas, fetchHeroi } from "@/lib/api";
import { supabase } from "@/integrations/supabase/client";
import { Trophy, Lock, Brain, Swords, Flame, Coins, Shield, Sparkles, Target, Eye, Waves, Crown, Star, CheckCircle2, BookOpen, Zap, Compass, Heart, ChevronLeft, ChevronRight } from "lucide-react";

type Grupo = "todas" | "mente" | "jornada" | "consistencia" | "batalha" | "riqueza" | "autodomínio";
type Raridade = "comum" | "rara" | "epica" | "lendaria";
type Item = { tipo:string; titulo:string; descricao:string; como:string; unlocked:boolean; progresso?:string; percent:number; desbloqueada_em?:string|null; grupo:Exclude<Grupo,"todas">; raridade:Raridade; icon:any; atributo:string };
type Reward = { xp:number; ouro:number; vida:number; atributo:string; atributo_delta:number; raridade:string; niveis?:number };
const GROUPS=[{id:"todas",label:"Todas",icon:Trophy},{id:"jornada",label:"Jornada",icon:Compass},{id:"mente",label:"Mente",icon:Brain},{id:"consistencia",label:"Constância",icon:Flame},{id:"batalha",label:"Batalha",icon:Swords},{id:"autodomínio",label:"Autodomínio",icon:Shield},{id:"riqueza",label:"Riqueza",icon:Coins}] as const;
const RARITY:Record<Raridade,{label:string;className:string;glow:string}>={comum:{label:"COMUM",className:"border-border text-muted-foreground",glow:""},rara:{label:"RARA",className:"border-cyan-400/50 text-cyan-300",glow:"shadow-[0_0_18px_rgba(34,211,238,.12)]"},epica:{label:"ÉPICA",className:"border-purple-400/60 text-purple-300",glow:"shadow-[0_0_22px_rgba(168,85,247,.18)]"},lendaria:{label:"LENDÁRIA",className:"border-amber-300/70 text-amber-200",glow:"shadow-[0_0_28px_rgba(251,191,36,.2)]"}};
const ATTR_LABEL:Record<string,string>={consciencia:"Consciência",foco:"Foco",autodominio:"Autodomínio",coragem:"Coragem",disciplina:"Disciplina",gestao:"Gestão",resiliencia:"Resiliência"};
const ATTR_ICON:Record<string,any>={consciencia:Brain,foco:Target,autodominio:Shield,coragem:Swords,disciplina:Flame,gestao:Coins,resiliencia:Heart};
function loadDiary(uid:string){try{return JSON.parse(localStorage.getItem(`ascensao:diario:${uid}`)||"[]") as Array<{date:string;text:string;type:string}>}catch{return[]}}

export default function ConquistasPage(){
 const {user}=useAuth(); const uid=user?.id;
 const {data:cs,isLoading}=useQuery({queryKey:["conq",uid],queryFn:()=>fetchConquistas(uid!),enabled:!!uid});
 const {data:heroi}=useQuery({queryKey:["heroi",uid],queryFn:()=>fetchHeroi(uid!),enabled:!!uid});
 const {data:attrs}=useQuery({queryKey:["hero-attributes",uid],queryFn:async()=>{const {data}=await supabase.from("hero_attributes").select("*").eq("user_id",uid!).maybeSingle();return data},enabled:!!uid});
 const {data:kills}=useQuery({queryKey:["kills-conq",uid],queryFn:async()=>{const {count}=await supabase.from("inimigo").select("id",{count:"exact",head:true}).eq("user_id",uid!).eq("ativo",false);return count??0},enabled:!!uid});
 const {data:economia}=useQuery({queryKey:["econ-conq",uid],queryFn:async()=>{const {data}=await supabase.from("transacoes_ouro").select("valor,origem").eq("user_id",uid!);const r=data??[];return{ganho:r.filter(x=>(x.valor??0)>0).reduce((s,x)=>s+(x.valor??0),0),compras:r.filter(x=>(x.origem??"")==="loja").length}},enabled:!!uid});
 const {data:pureza}=useQuery({queryKey:["pureza-conq",uid],queryFn:async()=>{const {data}=await supabase.from("habito_logs").select("data,completado,habitos!inner(tipo)").eq("user_id",uid!).eq("completado",true);const days=new Map<string,{p:number;n:number}>();for(const l of data??[]){const d=l.data as string,t=(l as any).habitos?.tipo as string,x=days.get(d)??{p:0,n:0};if(t==="positivo")x.p++;if(t==="negativo")x.n++;days.set(d,x)}let clean=0;for(const x of days.values())if(x.p>0&&x.n===0)clean++;return clean},enabled:!!uid});
 const [diary,setDiary]=useState<Array<{date:string;text:string;type:string}>>([]),[filtro,setFiltro]=useState<Grupo>("todas"),[aberta,setAberta]=useState<string|null>(null),[reward,setReward]=useState<Reward|null>(null),[rewardTitle,setRewardTitle]=useState(""),[claimed,setClaimed]=useState<Set<string>>(new Set());
 const catRef=useRef<HTMLDivElement>(null),claimStarted=useRef(false); useEffect(()=>{if(uid)setDiary(loadDiary(uid))},[uid]);
 const catalog=useMemo<Item[]>(()=>{if(!heroi)return[];const map=new Map((cs??[]).map(c=>[c.tipo,c] as const)),items:Item[]=[];const nivel=heroi.nivel??1,streak=heroi.streak_atual??0,ouro=heroi.ouro??0,ganho=economia?.ganho??0,compras=economia?.compras??0,derrotas=kills??0,clean=pureza??0,count=diary.length,dates=new Set(diary.map(x=>x.date)).size,urges=diary.filter(x=>x.type==="urge").length,choices=diary.filter(x=>/ESCOLHA:\s*(?!não registrada)/i.test(x.text)).length,perspectives=diary.filter(x=>/PERSPECTIVA:\s*(?!não registrada)/i.test(x.text)).length,thoughts=diary.filter(x=>/PENSAMENTO:/i.test(x.text)).length;const add=(x:Omit<Item,"percent">&{percent?:number})=>items.push({...x,percent:x.unlocked?100:Math.max(0,Math.min(99,x.percent??0))});const unlock=(t:string,c:boolean)=>c||map.has(t),db=(t:string)=>map.get(t)?.desbloqueada_em??null,tier=(n:number,k:string):Raridade=>k==="level"?(n>=50?"lendaria":n>=20?"epica":n>=10?"rara":"comum"):k==="streak"?(n>=60?"lendaria":n>=14?"epica":"rara"):k==="enemy"?(n>=10?"lendaria":n>=5?"epica":"rara"):(n>=5000?"lendaria":n>=1000?"epica":"rara"),attr=(g:Exclude<Grupo,"todas">)=>g==="mente"?"consciencia":g==="consistencia"?"disciplina":g==="batalha"?"coragem":g==="riqueza"?"gestao":g==="autodomínio"?"autodominio":g==="jornada"?"resiliencia":"foco";const m=(tipo:string,titulo:string,desc:string,como:string,current:number,goal:number,grupo:Exclude<Grupo,"todas">,raridade:Raridade,icon:any)=>{const u=unlock(tipo,current>=goal);add({tipo,titulo,descricao:desc,como,unlocked:u,progresso:u?undefined:`${Math.min(current,goal)}/${goal}`,percent:current/goal*100,desbloqueada_em:u?db(tipo):null,grupo,raridade,icon,atributo:attr(grupo)})};
  for(const n of [2,3,4,5,7,10,15,20,30,50,75,100])m(`nivel_${n}`,`Nível ${n}`,`Alcance o nível ${n} e avance mais um capítulo.`,`Continue acumulando XP.`,nivel,n,"jornada",tier(n,"level"),Sparkles);
  for(const n of [1,2,3,5,7,10,14,21,30,45,60,100])m(`diario_${n}`,`Diário ${n}`,`Seu diário virou parte da campanha.`,`Faça ${n} registros.`,count,n,"jornada",n>=30?"epica":n>=10?"rara":"comum",BookOpen);
  for(const n of [1,2,3,5,7,14,30])m(`dias_mente_${n}`,`${n} dia${n>1?"s":""} de presença`,`Você voltou para observar a própria experiência.`,`Registre o Diário em ${n} dia${n>1?"s":""} diferentes.`,dates,n,"mente",n>=14?"epica":n>=5?"rara":"comum",Compass);
  for(const n of [1,2,3,5,7,10])m(`escolhas_${n}`,`Escolha consciente ${n}`,`Você praticou pausar e escolher.`,`Registre ${n} escolhas conscientes.`,choices,n,"mente",n>=7?"epica":n>=3?"rara":"comum",Target);
  for(const n of [1,2,3,5,10])m(`perspectivas_${n}`,`Outra perspectiva ${n}`,`Você investigou uma interpretação.`,`Registre ${n} perspectivas alternativas.`,perspectives,n,"mente",n>=5?"epica":"rara",Eye);
  for(const n of [1,2,3,5,10])m(`vontades_${n}`,`Vontade ≠ comando ${n}`,`Você observou uma vontade sem obedecer automaticamente.`,`Registre ${n} experiências de vontade.`,urges,n,"mente",n>=5?"epica":"rara",Waves);
  for(const n of [1,3,5,10])m(`pensamentos_${n}`,`Observador ${n}`,`Você aprendeu a olhar para o pensamento de fora.`,`Registre ${n} pensamentos.`,thoughts,n,"mente",n>=5?"epica":"rara",Brain);
  for(const n of [1,2,3,5,7,10,14,21,30,45,60,100])m(`streak_${n}`,`${n} dia${n>1?"s":""} de constância`,`A campanha continua porque você voltou.`,`Mantenha ${n} dias seguidos.`,streak,n,"consistencia",n>=60?"lendaria":n>=14?"epica":n>=7?"rara":"comum",Flame);
  m("bau_lendario","Primeiro loot","Consistência também gera recompensas.","Abra o baú diário.",heroi.ultimo_bau_data?1:0,1,"consistencia","rara",Star);
  for(const n of [1,2,3,5,7,10,15,25])m(n===1?"primeiro_inimigo_derrotado":`inimigos_${n}`,n===1?"Primeiro inimigo derrotado":`${n} inimigos derrotados`,`Um padrão a menos controlando a campanha.`,`Derrote ${n} inimigo${n>1?"s":""}.`,derrotas,n,"batalha",tier(n,"enemy"),Swords);
  for(const n of [100,250,500,1000,2500,5000,10000])m(`ouro_ganho_${n}`,`${n.toLocaleString("pt-BR")} de ouro`,`Seu esforço virou recursos.`,`Acumule ${n.toLocaleString("pt-BR")} de ouro ganho.`,ganho,n,"riqueza",tier(n,"gold"),Coins);
  for(const n of [100,250,500,1000,2000,5000])m(`ouro_cofre_${n}`,`${n.toLocaleString("pt-BR")} guardados`,`Você aprendeu a acumular poder.`,`Mantenha ${n.toLocaleString("pt-BR")} de ouro.`,ouro,n,"riqueza",n>=5000?"lendaria":n>=1000?"epica":"rara",Coins);
  for(const n of [1,2,3,5,10,15,30])m(`compras_${n}`,`${n} compra${n>1?"s":""}`,`Use recursos para melhorar a jornada.`,`Faça ${n} compras na loja.`,compras,n,"riqueza",n>=15?"epica":n>=5?"rara":"comum",Coins);
  for(const n of [1,2,3,5,7,10,15,30])m(`dias_limpos_${n}`,`${n} dia${n>1?"s":""} limpo${n>1?"s":""}`,`Você escolheu construir sem alimentar a armadilha.`,`Tenha ${n} dias positivos e sem negativo concluído.`,clean,n,"autodomínio",n>=15?"epica":n>=5?"rara":"comum",Shield);
  return items},[heroi,cs,diary,kills,economia,pureza]);

 useEffect(()=>{if(!uid||!cs||claimStarted.current)return;claimStarted.current=true;(async()=>{for(const c of cs){const {data,error}=await supabase.rpc("claim_conquista_reward",{p_user_id:uid,p_conquista_id:c.id});if(!error&&data&&!data.claimed){setClaimed(s=>new Set(s).add(c.id));setRewardTitle(c.titulo??"Conquista desbloqueada");setReward(data as Reward);await new Promise(r=>setTimeout(r,850))}}})()},[uid,cs]);
 const total=catalog.length,obtidas=catalog.filter(x=>x.unlocked).length,percentual=total?Math.round(obtidas/total*100):0,filtrado=filtro==="todas"?catalog:catalog.filter(x=>x.grupo===filtro),ordered=[...filtrado].sort((a,b)=>a.unlocked!==b.unlocked?(a.unlocked?1:-1):b.percent-a.percent),proximas=catalog.filter(x=>!x.unlocked).sort((a,b)=>b.percent-a.percent).slice(0,3),attributes=["consciencia","foco","autodominio","coragem","disciplina","gestao","resiliencia"];
 const scrollCats=(dir:number)=>catRef.current?.scrollBy({left:dir*260,behavior:"smooth"});
 return <Shell><div className="mx-auto max-w-6xl space-y-5 pb-8">
  <header className="relative overflow-hidden rounded-3xl border border-primary/30 bg-card p-5 shadow-[0_0_40px_hsl(var(--primary)/.08)] sm:p-7"><div className="absolute -right-16 -top-16 h-40 w-40 rounded-full bg-primary/10 blur-3xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.28em] text-primary"><Trophy className="h-4 w-4"/> Sala de Troféus</div><h1 className="mt-2 font-display text-2xl tracking-[.14em] text-primary glow-text-purple sm:text-3xl">CONQUISTAS</h1><p className="mt-2 max-w-2xl text-xs leading-relaxed text-muted-foreground">Cada conquista é uma vitória jogável. Complete pequenas etapas, receba recursos e fortaleça seus atributos.</p></div><div className="rounded-2xl border border-primary/30 bg-primary/10 px-5 py-3 text-center"><div className="font-display text-2xl text-primary">{obtidas}/{total}</div><div className="text-[9px] font-black uppercase tracking-[.2em] text-muted-foreground">desbloqueadas</div></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-muted"><motion.div initial={{width:0}} animate={{width:`${percentual}%`}} className="h-full rounded-full bg-primary shadow-[0_0_14px_hsl(var(--primary)/.65)]"/></div></header>
  <section className="rounded-2xl border border-border bg-card/60 p-4"><div className="mb-3 flex items-center gap-2"><Zap className="h-4 w-4 text-amber-300"/><h2 className="font-display text-sm tracking-widest">ATRIBUTOS DO PERSONAGEM</h2></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{attributes.map(k=>{const I=ATTR_ICON[k];return <div key={k} className="rounded-xl border border-border bg-background/40 p-3"><div className="flex items-center gap-2 text-muted-foreground"><I className="h-3.5 w-3.5"/><span className="text-[9px] font-black uppercase tracking-wider">{ATTR_LABEL[k]}</span></div><div className="mt-1 font-display text-xl text-primary">{(attrs as any)?.[k]??0}</div></div>})}</div></section>
  {proximas.length>0&&<section><div className="mb-3 flex items-center gap-2"><Target className="h-4 w-4 text-primary"/><h2 className="font-display text-sm tracking-widest">PRÓXIMOS TROFÉUS</h2></div><div className="grid gap-3 md:grid-cols-3">{proximas.map(x=><div key={x.tipo} className="rounded-2xl border border-primary/20 bg-card p-4"><div className="flex items-center gap-3"><x.icon className="h-5 w-5 text-primary"/><div className="min-w-0"><div className="font-bold text-sm">{x.titulo}</div><div className="text-[9px] uppercase tracking-widest text-muted-foreground">{RARITY[x.raridade].label}</div></div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${x.percent}%`}}/></div><div className="mt-1 text-[9px] text-muted-foreground">{x.progresso} · XP + Ouro + Vida + atributo</div></div>)}</div></section>}
  <section className="relative flex items-center gap-1"><button onClick={()=>scrollCats(-1)} className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-primary/30 bg-card text-primary shadow-sm hover:bg-primary/10" aria-label="Ver categorias anteriores"><ChevronLeft className="h-4 w-4"/></button><div ref={catRef} className="flex min-w-0 flex-1 gap-2 overflow-x-auto scroll-smooth pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{GROUPS.map(g=>{const I=g.icon,active=filtro===g.id;return <button key={g.id} onClick={()=>setFiltro(g.id as Grupo)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-[10px] font-black uppercase tracking-wider transition ${active?"border-primary bg-primary/15 text-primary":"border-border bg-card text-muted-foreground hover:border-primary/40 hover:text-foreground"}`}><I className="h-3.5 w-3.5"/>{g.label}</button>})}</div><button onClick={()=>scrollCats(1)} className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-primary/30 bg-card text-primary shadow-sm hover:bg-primary/10" aria-label="Ver mais categorias"><ChevronRight className="h-4 w-4"/></button></section>
  {isLoading?<div className="py-10 text-center text-sm text-muted-foreground">Carregando campanha...</div>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ordered.map(x=>{const I=x.icon,open=aberta===x.tipo;return <motion.div key={x.tipo} layout onClick={()=>setAberta(open?null:x.tipo)} className={`cursor-pointer rounded-2xl border bg-card p-4 transition hover:border-primary/40 ${x.unlocked?RARITY[x.raridade].glow:"opacity-90"}`}><div className="flex items-start gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl border ${x.unlocked?RARITY[x.raridade].className:"border-border text-muted-foreground"}`}>{x.unlocked?<I className="h-5 w-5"/>:<Lock className="h-4 w-4"/>}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="font-bold text-sm">{x.titulo}</h3>{x.unlocked&&<CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400"/>}</div><div className={`mt-1 text-[9px] font-black uppercase tracking-[.16em] ${RARITY[x.raridade].className.split(" ").pop()}`}>{RARITY[x.raridade].label}</div></div></div><p className="mt-3 text-xs leading-relaxed text-muted-foreground">{x.descricao}</p>{!x.unlocked&&<><div className="mt-3 flex justify-between text-[9px] text-muted-foreground"><span>{x.progresso}</span><span>{Math.round(x.percent)}%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${x.percent}%`}}/></div></>}{open&&<div className="mt-3 rounded-xl border border-border bg-background/40 p-3 text-[10px] text-muted-foreground"><b className="text-foreground">Como desbloquear:</b> {x.como}<div className="mt-2 flex items-center gap-1.5 text-primary"><Sparkles className="h-3.5 w-3.5"/> Recompensa: XP + Ouro + Vida 1–5 + {ATTR_LABEL[x.atributo]}</div>{x.unlocked&&x.desbloqueada_em&&<div className="mt-2">Desbloqueada em {new Date(x.desbloqueada_em).toLocaleDateString("pt-BR")}</div>}</div>}</motion.div>})}</div>}
 </div><AnimatePresence>{reward&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><motion.div initial={{scale:.82,y:20}} animate={{scale:1,y:0}} className="w-full max-w-md rounded-3xl border border-amber-300/60 bg-card p-6 text-center shadow-[0_0_70px_rgba(251,191,36,.25)]"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl border border-amber-300/50 bg-amber-400/10 text-amber-200"><Trophy className="h-8 w-8"/></div><div className="mt-4 text-[10px] font-black uppercase tracking-[.3em] text-amber-300">CONQUISTA DESBLOQUEADA</div><h2 className="mt-2 font-display text-xl tracking-widest text-primary">{rewardTitle}</h2><p className="mt-2 text-xs text-muted-foreground">A vitória entrou no personagem. Sua recompensa foi aplicada.</p><div className="mt-5 grid grid-cols-2 gap-2 text-sm font-black"><div className="rounded-xl border border-primary/20 bg-primary/10 p-3 text-primary">⚡ +{reward.xp} XP</div><div className="rounded-xl border border-amber-300/20 bg-amber-300/10 p-3 text-amber-200">🪙 +{reward.ouro}</div><div className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-red-300">❤️ +{reward.vida}</div><div className="rounded-xl border border-purple-400/20 bg-purple-400/10 p-3 text-purple-300">🧬 +{reward.atributo_delta} {ATTR_LABEL[reward.atributo]??reward.atributo}</div></div>{(reward.niveis??0)>0&&<div className="mt-3 rounded-xl border border-primary/30 bg-primary/10 p-3 text-primary">⬆️ +{reward.niveis} nível{reward.niveis===1?"":"s"}</div>}<button onClick={()=>setReward(null)} className="mt-5 w-full rounded-xl border border-primary/40 bg-primary/10 px-4 py-3 text-xs font-black uppercase tracking-widest text-primary hover:bg-primary/20">Continuar campanha</button></motion.div></motion.div>}</AnimatePresence>
 </Shell>
}
