import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@/hooks/useAuth";
import Shell from "@/components/Shell";
import { fetchConquistas, fetchHeroi } from "@/lib/api";
import { supabase } from "@/integrations/supabase/client";
import { Trophy, Lock, Brain, Swords, Flame, Coins, Shield, Sparkles, BookOpen, Compass, Waves, CheckCircle2, Gift, Clock3 } from "lucide-react";

type Grupo = "todas" | "mente" | "jornada" | "consistencia" | "batalha" | "riqueza" | "autodomínio" | "jejum";
type Raridade = "comum" | "rara" | "epica" | "lendaria";
type Item = { tipo:string; titulo:string; descricao:string; como:string; unlocked:boolean; progresso?:string; percent:number; grupo:Exclude<Grupo,"todas">; raridade:Raridade; icon:any; atributo:string };
const GROUPS=[{id:"todas",label:"Todas",icon:Trophy},{id:"jornada",label:"Jornada",icon:Compass},{id:"mente",label:"Mente",icon:Brain},{id:"consistencia",label:"Constância",icon:Flame},{id:"batalha",label:"Batalha",icon:Swords},{id:"autodomínio",label:"Autodomínio",icon:Shield},{id:"riqueza",label:"Riqueza",icon:Coins},{id:"jejum",label:"Jejum",icon:Clock3}] as const;
const RARITY:Record<Raridade,{label:string;className:string}>={comum:{label:"COMUM",className:"border-border text-muted-foreground"},rara:{label:"RARA",className:"border-cyan-400/50 text-cyan-300"},epica:{label:"ÉPICA",className:"border-purple-400/60 text-purple-300"},lendaria:{label:"LENDÁRIA",className:"border-amber-300/70 text-amber-200"}};
const JEJUM_MAX_HOURS=21*24;
const JEJUM_MILESTONES=Array.from({length:Math.floor(JEJUM_MAX_HOURS/8)},(_,i)=>(i+1)*8);
const JEJUM_TITLES=Object.fromEntries(JEJUM_MILESTONES.map(h=>[h,`${h} Horas de Jejum`])) as Record<number,string>;
function loadDiary(uid:string){try{return JSON.parse(localStorage.getItem(`ascensao:diario:${uid}`)||"[]") as any[]}catch{return[]}}
function loadMaxFast(uid:string){try{const s=JSON.parse(localStorage.getItem(`ascensao:jejum:${uid}`)||"[]") as Array<{minutes:number}>;return Math.max(0,...s.map(x=>(x.minutes||0)/60))}catch{return 0}}
function rarity(h:number):Raridade{return h>=168?"lendaria":h>=72?"epica":h>=32?"rara":"comum"}

export default function ConquistasPage(){
 const {user}=useAuth();const uid=user?.id;const qc=useQueryClient();const [filter,setFilter]=useState<Grupo>("todas");const [diary,setDiary]=useState<any[]>([]);const [maxFast,setMaxFast]=useState(0);const [reward,setReward]=useState<string|null>(null);
 const {data:cs,isLoading}=useQuery({queryKey:["conq",uid],queryFn:()=>fetchConquistas(uid!),enabled:!!uid});
 const {data:hero}=useQuery({queryKey:["heroi",uid],queryFn:()=>fetchHeroi(uid!),enabled:!!uid});
 const {data:econ}=useQuery({queryKey:["econ-conq",uid],queryFn:async()=>{const {data}=await supabase.from("transacoes_ouro").select("valor,origem").eq("user_id",uid!);const rows=data??[];return{ganho:rows.filter(x=>(x.valor??0)>0).reduce((a,x)=>a+(x.valor??0),0),compras:rows.filter(x=>x.origem==="loja").length}},enabled:!!uid});
 useEffect(()=>{if(uid){setDiary(loadDiary(uid));setMaxFast(loadMaxFast(uid))}},[uid]);
 useEffect(()=>{if(!uid||maxFast<8)return;const rows=JEJUM_MILESTONES.filter(h=>maxFast>=h).map(h=>({user_id:uid,tipo:`jejum_${h}h`,titulo:JEJUM_TITLES[h],descricao:`Você alcançou ${h} horas de jejum em uma sessão registrada.`}));supabase.from("conquistas").upsert(rows,{onConflict:"user_id,tipo",ignoreDuplicates:true}).then(()=>qc.invalidateQueries({queryKey:["conq",uid]}))},[uid,maxFast,qc]);
 const items=useMemo<Item[]>(()=>{if(!hero)return[];const unlocked=new Set((cs??[]).map(x=>x.tipo));const result:Item[]=[];const add=(tipo:string,titulo:string,desc:string,como:string,current:number,goal:number,grupo:Exclude<Grupo,"todas">,raridade:Raridade,icon:any,atributo:string)=>result.push({tipo,titulo,descricao:desc,como,unlocked:current>=goal||unlocked.has(tipo),progresso:current>=goal||unlocked.has(tipo)?undefined:`${Math.min(current,goal)}/${goal}`,percent:Math.min(100,current/goal*100),grupo,raridade,icon,atributo});const nivel=hero.nivel??1,streak=hero.streak_atual??0,ouro=hero.ouro??0,count=diary.length,dates=new Set(diary.map(x=>x.date)).size,urges=diary.filter(x=>x.type==="urge").length,thoughts=diary.filter(x=>/PENSAMENTO:/i.test(x.text||"")).length,ganho=econ?.ganho??0,compras=econ?.compras??0;
 for(const n of [2,3,4,5,7,10,15,20,30,50,75,100])add(`nivel_${n}`,`Nível ${n}`,`Alcance o nível ${n}.`,`Continue acumulando XP.`,nivel,n,"jornada",n>=50?"lendaria":n>=20?"epica":n>=10?"rara":"comum",Sparkles,"resiliencia");
 for(const n of [1,2,3,5,7,10,14,21,30,45,60,100])add(`diario_${n}`,`Diário ${n}`,`Seu diário faz parte da campanha.`,`Faça ${n} registros.`,count,n,"jornada",n>=30?"epica":n>=10?"rara":"comum",BookOpen,"resiliencia");
 for(const n of [1,2,3,5,7,14,30])add(`dias_mente_${n}`,`${n} Dia${n>1?"s":""} De Presença`,`Você voltou para observar a própria experiência.`,`Registre o Diário em ${n} dia${n>1?"s":""} diferentes.`,dates,n,"mente",n>=14?"epica":n>=5?"rara":"comum",Compass,"consciencia");
 for(const n of [1,3,5,10])add(`pensamentos_${n}`,`Observador ${n}`,`Você observou pensamentos sem tratá-los como comandos.`,`Registre ${n} pensamentos.`,thoughts,n,"mente",n>=5?"epica":"rara",Brain,"consciencia");
 for(const n of [1,2,3,5,10])add(`vontades_${n}`,`Vontade ≠ Comando ${n}`,`Você observou uma vontade antes de agir.`,`Registre ${n} experiências de vontade.`,urges,n,"mente",n>=5?"epica":"rara",Waves,"consciencia");
 for(const n of [1,2,3,5,7,10,14,21,30,45,60,100])add(`streak_${n}`,`${n} Dia${n>1?"s":""} De Constância`,`A campanha continua porque você voltou.`,`Mantenha ${n} dias seguidos.`,streak,n,"consistencia",n>=60?"lendaria":n>=14?"epica":n>=7?"rara":"comum",Flame,"disciplina");
 for(const n of [1,2,3,5,7,10,15,25])add(n===1?"primeiro_inimigo_derrotado":`inimigos_${n}`,n===1?"Primeiro Inimigo Derrotado":`${n} Inimigos Derrotados`,`Um padrão a menos controlando a campanha.`,`Derrote ${n} inimigos.`,0,n,"batalha",n>=10?"lendaria":n>=5?"epica":"rara",Swords,"coragem");
 for(const n of [100,250,500,1000,2500,5000,10000])add(`ouro_ganho_${n}`,`${n.toLocaleString("pt-BR")} De Ouro`,`Seu esforço virou recursos.`,`Acumule ${n} de ouro ganho.`,ganho,n,"riqueza",n>=5000?"lendaria":n>=1000?"epica":"rara",Coins,"gestao");
 for(const n of [100,250,500,1000,2000,5000])add(`ouro_cofre_${n}`,`${n.toLocaleString("pt-BR")} Guardados`,`Você aprendeu a acumular poder.`,`Mantenha ${n} de ouro.`,ouro,n,"riqueza",n>=5000?"lendaria":n>=1000?"epica":"rara",Coins,"gestao");
 for(const n of [1,2,3,5,10,15,30])add(`compras_${n}`,`${n} Compra${n>1?"s":""}`,`Use recursos para melhorar a jornada.`,`Faça ${n} compras.`,compras,n,"riqueza",n>=15?"epica":n>=5?"rara":"comum",Coins,"gestao");
 for(const h of JEJUM_MILESTONES)add(`jejum_${h}h`,JEJUM_TITLES[h],`Você registrou uma sessão de ${h} horas de jejum ou mais.`,`Registre uma sessão de pelo menos ${h} horas.`,maxFast,h,"jejum",rarity(h),Clock3,"autodominio");
 return result},[hero,cs,diary,maxFast,econ]);
 const filtered=items.filter(x=>filter==="todas"||x.grupo===filter);
 const claim=async(item:Item)=>{if(!uid||!item.unlocked)return;const {data,error}=await (supabase.rpc as any)("claim_conquista_reward",{p_user_id:uid,p_conquista_id:item.tipo});if(!error&&data){setReward(`${item.titulo} • +${data.xp} XP • +${data.ouro} Ouro • +${data.vida} Vida`);qc.invalidateQueries({queryKey:["heroi",uid]})}};
 return <Shell><div className="min-h-screen px-4 py-6 md:px-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs tracking-[.3em] text-primary">ASCENSÃO • PROGRESSÃO</p><h1 className="mt-1 text-3xl font-black">CONQUISTAS</h1><p className="mt-1 text-sm text-muted-foreground">Cada marco registrado vira parte da sua campanha.</p></div><Trophy className="h-10 w-10 text-primary"/></div><div className="mb-6 flex gap-2 overflow-x-auto pb-2">{GROUPS.map(g=>{const I=g.icon;return <button key={g.id} onClick={()=>setFilter(g.id)} className={`flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold ${filter===g.id?"border-primary bg-primary/10 text-primary":"border-border bg-card text-muted-foreground"}`}><I className="h-4 w-4"/>{g.label}</button>})}</div>{isLoading||!hero?<div className="py-20 text-center text-muted-foreground">Carregando conquistas...</div>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(item=>{const I=item.icon;return <motion.button key={item.tipo} layout onClick={()=>item.unlocked&&claim(item)} className={`text-left rounded-2xl border bg-card/80 p-4 ${RARITY[item.raridade].className}`}><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-background"><I className="h-5 w-5"/></div><span className="text-[10px] font-black tracking-widest">{RARITY[item.raridade].label}</span></div><div className="mt-4 flex items-center gap-2"><h3 className="font-black">{item.titulo}</h3>{item.unlocked?<CheckCircle2 className="h-4 w-4 text-emerald-400"/>:<Lock className="h-4 w-4 text-muted-foreground"/>}</div><p className="mt-1 text-xs text-muted-foreground">{item.descricao}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:`${item.percent}%`}}/></div>{item.progresso&&<p className="mt-1 text-[10px] text-muted-foreground">{item.progresso}</p>}<p className="mt-3 text-[10px] text-primary">Atributo: {item.atributo}</p></motion.button>})}</div>}{reward&&<div className="fixed inset-x-4 bottom-4 z-50 mx-auto max-w-md rounded-2xl border border-primary/40 bg-background/95 p-4 shadow-2xl"><div className="flex items-center gap-3"><Gift className="h-6 w-6 text-primary"/><p className="text-sm font-bold">{reward}</p></div><button className="mt-3 w-full rounded-xl bg-primary py-2 text-sm font-black text-primary-foreground" onClick={()=>setReward(null)}>Continuar</button></div>}</div></div></Shell>;
}
