import Shell from "@/components/Shell";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, Compass, History, Lock, Moon, PenLine, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const perguntas = [
  { fase: "O ponto de partida", pergunta: "Seja honesto consigo: como você se sente em relação à vida que está vivendo hoje?", ajuda: "Não procure a resposta perfeita. Escreva o que realmente vier à cabeça." },
  { fase: "Consciência", pergunta: "O que mais está impedindo você de viver a vida que gostaria?", ajuda: "Pode ser um hábito, comportamento, medo, ambiente, decisão ou algo que você vem adiando." },
  { fase: "Padrões", pergunta: "Qual comportamento você continua repetindo, mesmo sabendo que ele não combina com a pessoa que quer ser?", ajuda: "Olhe para o que acontece de verdade, não para o que você gostaria que acontecesse." },
  { fase: "Consequência", pergunta: "Se nada mudar, como sua vida provavelmente estará daqui a um ano?", ajuda: "Imagine que os próximos 12 meses sejam iguais aos últimos. O que você terá ganhado e perdido?" },
  { fase: "Verdade", pergunta: "O que você sabe que precisa fazer, mas continua adiando?", ajuda: "Qual é aquela coisa que você já sabe, mas ainda não transformou em ação?" },
  { fase: "Direção", pergunta: "Se você pudesse construir uma nova fase da sua vida, o que gostaria que fosse diferente?", ajuda: "Pense em saúde, trabalho, relacionamentos, dinheiro, experiências, rotina e quem você quer ser." },
  { fase: "Identidade", pergunta: "Que tipo de pessoa você precisa começar a ser para construir essa vida?", ajuda: "Escolha qualidades e comportamentos que possam ser vistos nas suas ações." },
];

const KEY = "new-lifeup-noite-zero";

type Sessao = { id: string; data: string; respostas: { pergunta: string; resposta: string }[]; visao: string; decisao: string; compromissos: string[] };

export default function NoiteZero() {
  const [sessao, setSessao] = useState<Sessao | null>(() => { try { return JSON.parse(localStorage.getItem(KEY) || "null"); } catch { return null; } });
  const [tela, setTela] = useState<"inicio" | "guiado" | "visao" | "decisao" | "final" | "historico">(sessao ? "final" : "inicio");
  const [indice, setIndice] = useState(0);
  const [respostas, setRespostas] = useState<{ pergunta: string; resposta: string }[]>([]);
  const [texto, setTexto] = useState("");
  const [visao, setVisao] = useState("");
  const [decisao, setDecisao] = useState("");
  const [compromissos, setCompromissos] = useState(["", "", ""]);
  const [historico, setHistorico] = useState<Sessao[]>(() => { try { return JSON.parse(localStorage.getItem(`${KEY}-historico`) || "[]"); } catch { return []; } });

  const progresso = useMemo(() => Math.round(((indice) / perguntas.length) * 100), [indice]);

  const iniciar = () => { setIndice(0); setTexto(""); setRespostas([]); setVisao(""); setDecisao(""); setCompromissos(["", "", ""]); setTela("guiado"); };
  const responder = () => {
    if (!texto.trim()) return;
    const nova = [...respostas, { pergunta: perguntas[indice].pergunta, resposta: texto.trim() }];
    setRespostas(nova); setTexto("");
    if (indice + 1 < perguntas.length) setIndice(indice + 1); else setTela("visao");
  };
  const selar = () => {
    const lista = compromissos.filter(Boolean);
    if (!decisao.trim() || !lista.length) return;
    const nova: Sessao = { id: crypto.randomUUID(), data: new Date().toISOString(), respostas, visao, decisao, compromissos: lista };
    const novasHistorias = [...historico, nova];
    localStorage.setItem(KEY, JSON.stringify(nova));
    localStorage.setItem(`${KEY}-historico`, JSON.stringify(novasHistorias));
    setHistorico(novasHistorias); setSessao(nova); setTela("final");
  };

  return <Shell><div className="mx-auto max-w-3xl space-y-4 pb-10">
    <header className="rpg-panel overflow-hidden p-5 sm:p-7"><Link to="/mente" className="mb-5 inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-muted-foreground hover:text-primary"><ArrowLeft className="h-3.5 w-3.5" /> Mente</Link><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl border border-primary/40 bg-primary/10 text-primary shadow-[0_0_30px_hsl(var(--primary)/0.16)]"><Moon className="h-7 w-7" /></div><div><div className="text-[10px] font-black uppercase tracking-[0.3em] text-primary">EXPERIÊNCIA DE TRANSFORMAÇÃO</div><h1 className="mt-2 font-display text-2xl tracking-[0.16em] sm:text-3xl">NOITE ZERO</h1><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Uma conversa guiada com você mesmo. Uma pergunta por vez. Uma resposta de cada vez.</p></div></div></header>

    {tela === "inicio" && <div className="space-y-4"><section className="rpg-panel relative overflow-hidden p-6 sm:p-8"><div className="absolute -right-16 -top-16 h-40 w-40 rounded-full bg-primary/10 blur-3xl"/><div className="relative"><div className="mb-5 flex items-center gap-2 text-primary"><Sparkles className="h-4 w-4"/><span className="text-[10px] font-black uppercase tracking-[0.25em]">Sem pressa</span></div><h2 className="font-display text-2xl tracking-widest">VAMOS COMEÇAR?</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">Eu vou conduzir você. Você não precisa saber o que escrever antes de começar. Apenas responda à pergunta que aparecer e avance quando sentir que terminou.</p><button onClick={iniciar} className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3.5 text-xs font-black uppercase tracking-wider text-primary-foreground shadow-[0_0_25px_hsl(var(--primary)/0.25)] transition hover:scale-[1.01]">Começar Noite Zero <ArrowRight className="h-4 w-4"/></button></div></section><div className="grid gap-3 sm:grid-cols-2"><InfoCard icon={<PenLine/>} title="Journaling guiado" text="Você responde. O app conduz o próximo passo."/><InfoCard icon={<History/>} title="Seu histórico" text="Cada Noite Zero concluída fica registrada para você revisitar."/></div>{historico.length > 0 && <button onClick={() => setTela("historico")} className="rpg-panel flex w-full items-center gap-3 p-4 text-left hover:border-primary/50"><History className="h-5 w-5 text-primary"/><div className="flex-1"><div className="text-xs font-black uppercase tracking-wider">Histórico</div><div className="text-[11px] text-muted-foreground">Ver suas decisões anteriores</div></div><ArrowRight className="h-4 w-4 text-muted-foreground"/></button>}</div>}

    {tela === "guiado" && <section className="rpg-panel overflow-hidden p-5 sm:p-7"><Progress current={indice + 1} total={perguntas.length} value={progresso}/><div className="mt-8"><div className="text-[9px] font-black uppercase tracking-[0.25em] text-primary">{perguntas[indice].fase} · PERGUNTA {indice + 1}</div><h2 className="mt-3 font-display text-xl leading-relaxed tracking-wider sm:text-2xl">{perguntas[indice].pergunta}</h2><p className="mt-3 text-xs leading-relaxed text-muted-foreground">{perguntas[indice].ajuda}</p><textarea autoFocus value={texto} onChange={(e) => setTexto(e.target.value)} onKeyDown={(e) => { if ((e.ctrlKey || e.metaKey) && e.key === "Enter") responder(); }} placeholder="Escreva sua resposta..." className="mt-6 min-h-48 w-full resize-y rounded-2xl border border-border bg-background/50 p-4 text-sm leading-relaxed outline-none transition focus:border-primary/60 focus:ring-2 focus:ring-primary/10"/><div className="mt-4 flex items-center justify-between gap-3"><button onClick={() => { if (indice > 0) { setIndice(indice - 1); setTexto(respostas[indice - 1]?.resposta || ""); setRespostas(respostas.slice(0, -1)); } }} disabled={indice === 0} className="inline-flex items-center gap-1 rounded-xl border border-border px-4 py-3 text-[10px] font-black uppercase tracking-wider disabled:opacity-30"><ChevronLeft className="h-4 w-4"/> Voltar</button><button onClick={responder} disabled={!texto.trim()} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-[10px] font-black uppercase tracking-wider text-primary-foreground disabled:opacity-40">{indice + 1 === perguntas.length ? "Continuar" : "Próxima pergunta"}<ArrowRight className="h-4 w-4"/></button></div></div></section>}

    {tela === "visao" && <Editor title="AGORA OLHE PARA FRENTE" subtitle="Se você realmente começar a agir diferente, como gostaria que sua vida estivesse daqui a 12 meses?" value={visao} setValue={setVisao} button="Construir minha decisão" onNext={() => setTela("decisao")} />}

    {tela === "decisao" && <section className="rpg-panel p-5 sm:p-7"><div className="flex items-center gap-2 text-primary"><Lock className="h-4 w-4"/><span className="text-[10px] font-black uppercase tracking-[0.25em]">O momento da decisão</span></div><h2 className="mt-4 font-display text-xl tracking-widest">O QUE MUDA A PARTIR DE HOJE?</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Agora transforme tudo que escreveu em uma decisão simples, concreta e praticável.</p><textarea value={decisao} onChange={(e) => setDecisao(e.target.value)} placeholder="A partir de hoje, eu decido..." className="mt-5 min-h-32 w-full rounded-2xl border border-border bg-background/50 p-4 text-sm leading-relaxed outline-none focus:border-primary/60"/><div className="mt-6"><h3 className="text-xs font-black uppercase tracking-wider">Quais ações vão provar essa decisão?</h3><div className="mt-3 space-y-2">{compromissos.map((c,i)=><input key={i} value={c} onChange={(e)=>setCompromissos(a=>a.map((x,j)=>j===i?e.target.value:x))} placeholder={`Ação ${i+1}`} className="w-full rounded-xl border border-border bg-background/50 px-4 py-3 text-xs outline-none focus:border-primary/60"/>)}</div></div><button onClick={selar} disabled={!decisao.trim() || !compromissos.some(Boolean)} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3.5 text-xs font-black uppercase tracking-wider text-primary-foreground disabled:opacity-40"><Lock className="h-4 w-4"/> Selar minha decisão</button></section>}

    {tela === "final" && sessao && <Final sessao={sessao} onHistorico={() => setTela("historico")} onNova={iniciar}/>} 
    {tela === "historico" && <Historico historico={historico} onBack={() => setTela(sessao ? "final" : "inicio")} />}
  </div></Shell>;
}

function Progress({current,total,value}:{current:number;total:number;value:number}) { return <div><div className="flex items-center justify-between text-[9px] font-black uppercase tracking-wider text-muted-foreground"><span>Jornada</span><span>{current} / {total}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all duration-500" style={{width:`${Math.max(8,value)}%`}}/></div></div>; }
function Editor({title,subtitle,value,setValue,button,onNext}:{title:string;subtitle:string;value:string;setValue:(v:string)=>void;button:string;onNext:()=>void}) { return <section className="rpg-panel p-5 sm:p-7"><div className="text-[10px] font-black uppercase tracking-[0.25em] text-primary">{title}</div><h2 className="mt-4 font-display text-xl tracking-widest">SUA VISÃO</h2><p className="mt-3 text-xs leading-relaxed text-muted-foreground">{subtitle}</p><textarea autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder="Descreva a vida que você quer construir..." className="mt-6 min-h-52 w-full resize-y rounded-2xl border border-border bg-background/50 p-4 text-sm leading-relaxed outline-none focus:border-primary/60"/><button onClick={onNext} disabled={!value.trim()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-xs font-black uppercase tracking-wider text-primary-foreground disabled:opacity-40">{button}<ArrowRight className="h-4 w-4"/></button></section>; }
function InfoCard({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <div className="rpg-panel p-4"><div className="mb-3 grid h-9 w-9 place-items-center rounded-xl border border-primary/30 bg-primary/10 text-primary">{icon}</div><h3 className="text-xs font-black uppercase tracking-wider">{title}</h3><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{text}</p></div>; }
function Final({sessao,onHistorico,onNova}:{sessao:Sessao;onHistorico:()=>void;onNova:()=>void}) { return <section className="space-y-4"><div className="rpg-panel border-primary/40 bg-primary/5 p-6 text-center sm:p-8"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-primary/50 bg-primary/10 text-primary"><Check className="h-8 w-8"/></div><div className="mt-5 text-[10px] font-black uppercase tracking-[0.3em] text-primary">DECISÃO SELADA</div><h2 className="mt-2 font-display text-2xl tracking-widest">O PRÓXIMO CAPÍTULO COMEÇA AGORA.</h2><p className="mx-auto mt-3 max-w-xl text-xs leading-relaxed text-muted-foreground">Sua reflexão virou uma decisão. Agora suas ações podem transformar essa decisão em evidência.</p></div><div className="rpg-panel p-5"><div className="text-[9px] font-black uppercase tracking-[0.25em] text-muted-foreground">Minha decisão</div><p className="mt-2 text-sm leading-relaxed">{sessao.decisao}</p><div className="mt-5 space-y-2">{sessao.compromissos.map((c,i)=><div key={i} className="flex items-center gap-3 rounded-xl border border-border bg-background/30 p-3 text-xs"><Check className="h-4 w-4 shrink-0 text-primary"/>{c}</div>)}</div></div><div className="grid gap-2 sm:grid-cols-2"><button onClick={onHistorico} className="rpg-panel flex items-center justify-center gap-2 p-4 text-xs font-black uppercase tracking-wider hover:border-primary/50"><History className="h-4 w-4 text-primary"/> Histórico</button><button onClick={onNova} className="rpg-panel flex items-center justify-center gap-2 p-4 text-xs font-black uppercase tracking-wider hover:border-primary/50"><Sparkles className="h-4 w-4 text-primary"/> Nova reflexão</button></div></section>; }
function Historico({historico,onBack}:{historico:Sessao[];onBack:()=>void}) { return <section className="space-y-3"><button onClick={onBack} className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-muted-foreground hover:text-primary"><ChevronLeft className="h-4 w-4"/> Voltar</button><div className="rpg-panel p-5"><div className="flex items-center gap-2 text-primary"><History className="h-4 w-4"/><span className="text-[10px] font-black uppercase tracking-[0.25em]">Histórico da jornada</span></div><h2 className="mt-3 font-display text-xl tracking-widest">SUAS NOITES ZERO</h2></div>{[...historico].reverse().map((s)=><article key={s.id} className="rpg-panel p-5"><div className="flex items-center justify-between gap-3"><span className="text-[9px] font-black uppercase tracking-wider text-primary">{new Date(s.data).toLocaleDateString("pt-BR")}</span><span className="text-[9px] text-muted-foreground">{s.respostas.length} reflexões</span></div><h3 className="mt-3 text-sm font-black">Sua decisão</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{s.decisao}</p><details className="mt-4"><summary className="cursor-pointer text-[10px] font-black uppercase tracking-wider text-primary">Ver reflexão completa</summary><div className="mt-3 space-y-3">{s.respostas.map((r,i)=><div key={i} className="rounded-xl border border-border bg-background/20 p-3"><div className="text-[9px] font-black uppercase tracking-wider text-muted-foreground">Pergunta {i+1}</div><p className="mt-1 text-xs font-semibold">{r.pergunta}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{r.resposta}</p></div>)}{s.visao && <div className="rounded-xl border border-primary/20 bg-primary/5 p-3"><div className="text-[9px] font-black uppercase tracking-wider text-primary">Visão</div><p className="mt-1 text-xs leading-relaxed">{s.visao}</p></div>}</div></details></article>)}</section>; }
