import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import Shell from "@/components/Shell";
import RichTextEditor from "@/components/RichTextEditor";
import { CalendarDays, Clock3, ExternalLink, FolderKanban, GripVertical, LayoutGrid, Link2, Pencil, Plus, Search, Target, Trash2, X } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { getOrMigrateLegacyState, setUserState } from "@/lib/userState";

type Status = "Backlog" | "A Fazer" | "Em Produção" | "Revisão" | "Concluído";
type Priority = "Baixa" | "Média" | "Alta";
type Task = { id: string; title: string; status: Status; due: string; priority: Priority; links: string; notes: string };
type Project = { id: string; title: string; goal: string; start: string; due: string; description: string; links: string; notes: string; tasks: Task[] };
const STATUSES: Status[] = ["Backlog", "A Fazer", "Em Produção", "Revisão", "Concluído"];
const STATE_KEY = "projetos";
const legacyKey = "ascensao:projetos";
const statusIcon: Record<Status, string> = { Backlog: "○", "A Fazer": "◐", "Em Produção": "◉", Revisão: "◈", Concluído: "✓" };
const blankProject = (): Project => ({ id: crypto.randomUUID(), title: "Novo Projeto", goal: "", start: "", due: "", description: "", links: "", notes: "", tasks: [] });
const blankTask = (): Task => ({ id: crypto.randomUUID(), title: "", status: "A Fazer", due: "", priority: "Média", links: "", notes: "" });
function daysLeft(date: string) { if (!date) return null; return Math.ceil((new Date(`${date}T23:59:59`).getTime() - Date.now()) / 86400000); }
function progress(project: Project) { return project.tasks.length ? Math.round(project.tasks.filter(t => t.status === "Concluído").length / project.tasks.length * 100) : 0; }

function ProjectEditor({ project, onChange, onClose }: { project: Project; onChange: (p: Project) => void; onClose: () => void }) {
  const remaining = daysLeft(project.due); const update = (patch: Partial<Project>) => onChange({ ...project, ...patch });
  useEffect(() => { const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previousOverflow; }; }, []);
  const content = <div className="fixed inset-0 z-[2147483647] isolate flex min-h-[100dvh] w-screen items-start justify-center overflow-y-auto bg-black p-3 backdrop-blur-xl sm:items-center sm:p-6"><div className="pointer-events-auto relative z-[2147483647] my-auto w-full max-w-3xl overflow-hidden rounded-[28px] border border-white/10 bg-[#08080d] shadow-[0_30px_120px_rgba(0,0,0,.95)] shadow-fuchsia-950/40">
    <div className="flex items-center gap-3 border-b border-white/10 bg-white/[.025] px-5 py-4 sm:px-6"><div className="grid h-10 w-10 place-items-center rounded-xl border border-fuchsia-400/20 bg-fuchsia-500/10 text-fuchsia-300"><FolderKanban className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="text-[8px] font-black uppercase tracking-[.3em] text-fuchsia-300">Configurar projeto</p><h2 className="truncate font-display text-lg tracking-widest">{project.title || "Novo Projeto"}</h2></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 text-white/50 hover:bg-white/5 hover:text-white"><X className="h-4 w-4" /></button></div>
    <div className="space-y-5 p-5 sm:p-6"><div className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Nome do projeto</span><input autoFocus value={project.title} onChange={e => update({ title: e.target.value })} className="field" placeholder="Ex.: Lançamento do Estúdio" /></label><label className="sm:col-span-2"><span className="field-label">Objetivo principal</span><input value={project.goal} onChange={e => update({ goal: e.target.value })} className="field" placeholder="O que precisa estar realizado quando este projeto terminar?" /></label><label><span className="field-label">Início</span><input type="date" value={project.start} onChange={e => update({ start: e.target.value })} className="field" /></label><label><span className="field-label">Prazo final</span><input type="date" value={project.due} onChange={e => update({ due: e.target.value })} className="field" /></label></div><label><span className="field-label">Descrição e contexto</span><textarea value={project.description} onChange={e => update({ description: e.target.value })} className="field min-h-28 resize-y" placeholder="Contexto, escopo, resultado esperado..." /></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="field-label">Links importantes</span><input value={project.links} onChange={e => update({ links: e.target.value })} className="field" placeholder="https://..." /></label><div className="rounded-xl border border-white/10 bg-white/[.02] p-3"><span className="field-label">Prazo</span><p className={`mt-2 text-sm font-bold ${remaining !== null && remaining < 0 ? "text-red-300" : "text-fuchsia-200"}`}>{remaining === null ? "Nenhum prazo definido" : remaining < 0 ? `Atrasado ${Math.abs(remaining)} dias` : remaining === 0 ? "Vence hoje" : `${remaining} dias restantes`}</p></div></div><div><div className="mb-2 flex items-center justify-between"><span className="field-label mb-0">Notas gerais</span><span className="text-[7px] font-bold uppercase tracking-[.16em] text-white/20">Editor completo</span></div><RichTextEditor value={project.notes} onChange={notes => update({ notes })} placeholder="Decisões, ideias, referências, valores, observações..." minHeight="220px" /></div></div>
    <div className="flex justify-end border-t border-white/10 bg-white/[.015] px-5 py-4 sm:px-6"><button onClick={onClose} className="rounded-xl bg-fuchsia-500 px-5 py-2.5 text-[9px] font-black uppercase shadow-lg shadow-fuchsia-950/30">Concluir</button></div>
  </div></div>;
  return createPortal(content, document.body);
}

function TaskModal({ task, onSave, onClose }: { task: Task; onSave: (t: Task) => void; onClose: () => void }) {
  const [draft, setDraft] = useState(task); const patch = (p: Partial<Task>) => setDraft(v => ({ ...v, ...p }));
  useEffect(() => { const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previousOverflow; }; }, []);
  const content = <div className="fixed inset-0 z-[2147483647] isolate flex min-h-[100dvh] w-screen items-start justify-center overflow-y-auto bg-black p-3 backdrop-blur-xl sm:items-center sm:p-6"><div className="pointer-events-auto relative z-[2147483647] my-auto w-full max-w-2xl overflow-hidden rounded-[28px] border border-white/10 bg-[#08080d] shadow-[0_30px_120px_rgba(0,0,0,.95)] shadow-fuchsia-950/40">
    <div className="flex items-center gap-3 border-b border-white/10 bg-white/[.025] px-5 py-4"><div className="min-w-0 flex-1"><p className="text-[8px] font-black uppercase tracking-[.3em] text-fuchsia-300">Detalhes da etapa</p><h3 className="mt-1 truncate font-display tracking-wider">{draft.title || "Nova tarefa"}</h3><p className="mt-1 text-[9px] text-white/25">Tudo o que você registrar aqui pertence a esta etapa do projeto.</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 text-white/50 hover:bg-white/5 hover:text-white"><X className="h-4 w-4" /></button></div>
    <div className="max-h-[78vh] space-y-5 overflow-y-auto p-5 sm:p-6"><input autoFocus value={draft.title} onChange={e => patch({ title: e.target.value })} className="field text-base font-semibold" placeholder="Nome da tarefa" /><div className="grid gap-3 sm:grid-cols-2"><label><span className="field-label">Status</span><select value={draft.status} onChange={e => patch({ status: e.target.value as Status })} className="field">{STATUSES.map(s => <option key={s}>{s}</option>)}</select></label><label><span className="field-label">Prioridade</span><select value={draft.priority} onChange={e => patch({ priority: e.target.value as Priority })} className="field"><option>Baixa</option><option>Média</option><option>Alta</option></select></label><label><span className="field-label">Prazo</span><input type="date" value={draft.due} onChange={e => patch({ due: e.target.value })} className="field" /></label><label><span className="field-label">Link / referência</span><input value={draft.links} onChange={e => patch({ links: e.target.value })} className="field" placeholder="https://..." /></label></div><div><div className="mb-2 flex items-center justify-between"><span className="field-label mb-0">Anotações da etapa</span><span className="text-[7px] font-bold uppercase tracking-[.16em] text-fuchsia-300/50">Word mode</span></div><RichTextEditor value={draft.notes} onChange={notes => patch({ notes })} placeholder="Escreva tudo sobre esta etapa: contexto, decisões, ideias, checklist, valores R$, links, resultados..." minHeight="360px" /></div></div>
    <div className="flex justify-end gap-2 border-t border-white/10 bg-white/[.015] px-5 py-4"><button onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2.5 text-[9px] font-black uppercase text-white/50 hover:bg-white/5 hover:text-white">Cancelar</button><button onClick={() => { if (draft.title.trim()) onSave({ ...draft, title: draft.title.trim() }); }} className="rounded-xl bg-fuchsia-500 px-5 py-2.5 text-[9px] font-black uppercase shadow-lg shadow-fuchsia-950/30">Salvar tarefa</button></div>
  </div></div>;
  return createPortal(content, document.body);
}

function TaskCard({ task, onOpen, onDragStart, onDelete }: { task: Task; onOpen: () => void; onDragStart: () => void; onDelete: () => void }) { const priority = task.priority === "Alta" ? "text-red-300 border-red-400/20 bg-red-500/10" : task.priority === "Média" ? "text-amber-200 border-amber-300/20 bg-amber-500/10" : "text-white/40 border-white/10 bg-white/[.03]"; return <div draggable onDragStart={onDragStart} onClick={onOpen} className="group cursor-grab rounded-2xl border border-white/10 bg-[#0d0d14] p-3 shadow-lg transition hover:-translate-y-0.5 hover:border-fuchsia-300/20 hover:bg-[#101019] active:cursor-grabbing"><div className="flex items-start gap-1.5"><GripVertical className="mt-0.5 h-3.5 w-3.5 shrink-0 text-white/15 transition group-hover:text-fuchsia-300/50" /><p className="min-w-0 flex-1 text-[11px] font-semibold leading-4 text-white/85">{task.title || "Sem título"}</p><button onClick={e => { e.stopPropagation(); onDelete(); }} className="hidden rounded-md p-1 text-white/20 hover:bg-red-500/10 hover:text-red-300 group-hover:block"><Trash2 className="h-3 w-3" /></button></div><div className="mt-2 flex flex-wrap items-center gap-1"><span className={`rounded-full border px-1.5 py-0.5 text-[7px] font-black uppercase ${priority}`}>{task.priority}</span>{task.due && <span className="inline-flex items-center gap-1 rounded-full border border-white/10 px-1.5 py-0.5 text-[7px] text-white/35"><CalendarDays className="h-2.5 w-2.5" />{task.due.split("-").reverse().join("/")}</span>}{task.links && <Link2 className="h-3 w-3 text-fuchsia-300/60" />}{task.notes && <span className="rounded-full border border-fuchsia-300/10 bg-fuchsia-500/5 px-1.5 py-0.5 text-[7px] text-fuchsia-200/45">✎ notas</span>}</div></div>; }
function KanbanColumn({ status, tasks, onDrop, onOpen, onDragStart, onDelete, onAdd }: { status: Status; tasks: Task[]; onDrop: () => void; onOpen: (t: Task) => void; onDragStart: (id: string) => void; onDelete: (id: string) => void; onAdd: () => void }) { return <section onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); onDrop(); }} className="flex min-h-[340px] min-w-0 flex-1 flex-col rounded-[20px] border border-white/10 bg-white/[.018] p-2"><div className="flex items-center gap-1.5 px-1.5 py-2"><span className="text-xs text-fuchsia-300">{statusIcon[status]}</span><h3 className="min-w-0 truncate text-[8px] font-black uppercase tracking-[.14em] text-white/60">{status}</h3><span className="ml-auto grid h-5 min-w-5 shrink-0 place-items-center rounded-full bg-white/[.06] px-1.5 text-[7px] font-bold text-white/35">{tasks.length}</span></div><div className="flex flex-1 flex-col gap-1.5 overflow-y-auto pb-1">{tasks.map(t => <TaskCard key={t.id} task={t} onOpen={() => onOpen(t)} onDragStart={() => onDragStart(t.id)} onDelete={() => onDelete(t.id)} />)}{tasks.length === 0 && <div className="grid min-h-24 place-items-center rounded-xl border border-dashed border-white/8 text-center text-[8px] uppercase tracking-wider text-white/20">Arraste tarefas<br />para cá</div>}</div><button onClick={onAdd} className="mt-1 flex w-full items-center justify-center gap-1 rounded-lg border border-transparent py-1.5 text-[8px] font-black uppercase text-white/25 transition hover:border-fuchsia-300/10 hover:bg-fuchsia-500/5 hover:text-fuchsia-200"><Plus className="h-3 w-3" /> Adicionar</button></section>; }
export default function Projetos() {
  const { user } = useAuth(); const uid = user?.id; const [projects, setProjects] = useState<Project[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [query, setQuery] = useState(""); const [editingProject, setEditingProject] = useState(false); const [editingTask, setEditingTask] = useState<Task | null>(null); const [draggedTask, setDraggedTask] = useState<string | null>(null);
  useEffect(() => { if (!uid) return; void getOrMigrateLegacyState<Project[]>(uid, STATE_KEY, legacyKey, []).then(p => { setProjects(p); setSelectedId(p[0]?.id ?? null); }); }, [uid]);
  const save = (next: Project[]) => { setProjects(next); if (uid) void setUserState(uid, STATE_KEY, next); }; const selected = projects.find(p => p.id === selectedId) ?? null;
  const visibleProjects = projects.filter(p => !query.trim() || p.title.toLowerCase().includes(query.toLowerCase()) || p.goal.toLowerCase().includes(query.toLowerCase()));
  const stats = useMemo(() => ({ tasks: projects.reduce((n,p) => n+p.tasks.length,0), done: projects.reduce((n,p) => n+p.tasks.filter(t=>t.status === "Concluído").length,0), active: projects.filter(p=>progress(p)<100).length }), [projects]);
  const updateProject = (p: Project) => save(projects.map(x => x.id === p.id ? p : x)); const createProject = () => { const p=blankProject(); save([...projects,p]); setSelectedId(p.id); setEditingProject(true); }; const deleteProject = () => { if (!selected || !window.confirm(`Excluir o projeto “${selected.title}”? Esta ação não pode ser desfeita.`)) return; const next=projects.filter(p=>p.id!==selected.id); save(next); setSelectedId(next[0]?.id ?? null); }; const addTask = (status: Status) => { if (!selected) return; setEditingTask({ ...blankTask(), status }); }; const saveTask = (task: Task) => { if (!selected) return; updateProject({ ...selected, tasks: selected.tasks.some(t=>t.id===task.id) ? selected.tasks.map(t=>t.id===task.id?task:t) : [...selected.tasks,task] }); setEditingTask(null); }; const deleteTask = (id:string) => { if (!selected || !window.confirm("Excluir esta tarefa?")) return; updateProject({ ...selected, tasks:selected.tasks.filter(t=>t.id!==id) }); }; const moveDragged=(status:Status)=>{ if(!selected||!draggedTask)return; updateProject({...selected,tasks:selected.tasks.map(x=>x.id===draggedTask?{...x,status}:x)});setDraggedTask(null); };
  return <Shell><style>{`.field-label{display:block;margin-bottom:.4rem;font-size:8px;font-weight:900;text-transform:uppercase;letter-spacing:.2em;color:rgba(255,255,255,.38)}.field{display:block;width:100%;border-radius:.8rem;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.025);padding:.7rem .8rem;font-size:.8rem;color:rgba(255,255,255,.88);outline:none}.field:focus{border-color:rgba(217,70,239,.35);box-shadow:0 0 0 3px rgba(217,70,239,.08)}select.field option{background:#101018;color:white}.stat{border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.025);border-radius:.9rem;padding:.65rem .75rem}.stat span{display:block;font-size:7px;font-weight:900;text-transform:uppercase;letter-spacing:.16em;color:rgba(255,255,255,.28)}.stat b{display:block;margin-top:.25rem;font-family:inherit;font-size:1.1rem;color:rgba(255,255,255,.8)}`}</style><div className="space-y-5">
    <header className="rounded-[28px] border border-white/10 bg-gradient-to-br from-fuchsia-500/[.08] via-white/[.025] to-transparent p-5 shadow-2xl shadow-fuchsia-950/10 sm:p-6"><div className="flex flex-wrap items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl border border-fuchsia-300/20 bg-fuchsia-500/10 text-fuchsia-300"><LayoutGrid className="h-7 w-7" /></div><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.32em] text-fuchsia-300">Central de Projetos</p><h1 className="mt-1 font-display text-2xl tracking-[.14em] sm:text-3xl">PROJETOS</h1><p className="mt-2 max-w-2xl text-xs leading-5 text-white/40">Transforme ideias em execução. Organize objetivos, tarefas, prazos e decisões em um fluxo visual.</p></div><button onClick={createProject} className="inline-flex items-center gap-2 rounded-xl bg-fuchsia-500 px-4 py-2.5 text-[9px] font-black uppercase shadow-lg shadow-fuchsia-950/30"><Plus className="h-4 w-4" /> Novo projeto</button></div><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-4"><div className="stat"><span>Projetos</span><b>{projects.length}</b></div><div className="stat"><span>Tarefas</span><b>{stats.tasks}</b></div><div className="stat"><span>Concluídas</span><b className="text-fuchsia-300">{stats.done}</b></div><div className="stat hidden sm:block"><span>Em andamento</span><b>{stats.active}</b></div></div></header>
    <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/20" /><input value={query} onChange={e=>setQuery(e.target.value)} className="field pl-10" placeholder="Buscar projeto..." /></div>
    {projects.length>0 && <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{visibleProjects.map(p=><button key={p.id} onClick={()=>setSelectedId(p.id)} className={`group rounded-2xl border p-3 text-left transition ${selectedId===p.id?"border-fuchsia-300/25 bg-fuchsia-500/[.08] shadow-lg shadow-fuchsia-950/10":"border-white/10 bg-white/[.02] hover:bg-white/[.04]"}`}><div className="flex items-center gap-2"><FolderKanban className={`h-4 w-4 shrink-0 ${selectedId===p.id?"text-fuchsia-300":"text-white/25"}`} /><span className="truncate text-[10px] font-bold text-white/75">{p.title||"Sem título"}</span><span className="ml-auto shrink-0 text-[8px] text-white/30">{progress(p)}%</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-fuchsia-400" style={{width:`${progress(p)}%`}} /></div><div className="mt-2 text-[8px] text-white/30">{p.tasks.length} tarefas</div></button>)}</div>}
    {!selected ? <div className="rounded-[28px] border border-dashed border-white/10 bg-white/[.015] p-12 text-center"><Target className="mx-auto h-10 w-10 text-fuchsia-300/30" /><h2 className="mt-4 font-display tracking-widest text-white/60">SEU ESPAÇO DE EXECUÇÃO</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-white/30">Crie um projeto para abrir seu quadro Kanban e transformar planejamento em movimento.</p><button onClick={createProject} className="mt-5 rounded-xl bg-fuchsia-500 px-5 py-2.5 text-[9px] font-black uppercase">Criar meu primeiro projeto</button></div> : <><div className="flex flex-wrap items-center gap-3 rounded-[24px] border border-white/10 bg-white/[.025] p-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate font-display text-lg tracking-widest">{selected.title||"Sem título"}</h2><button onClick={()=>setEditingProject(true)} className="grid h-7 w-7 shrink-0 place-items-center rounded-lg text-white/30 hover:bg-fuchsia-500/10 hover:text-fuchsia-200"><Pencil className="h-3.5 w-3.5" /></button></div><p className="mt-1 truncate text-[10px] text-white/35">{selected.goal||"Defina o objetivo deste projeto."}</p></div><div className="flex items-center gap-2"><div className="hidden text-right sm:block"><p className="text-[7px] font-black uppercase tracking-widest text-white/25">Progresso</p><p className="font-display text-lg text-fuchsia-300">{progress(selected)}%</p></div>{selected.links && <a href={selected.links.split(/\s+/)[0]} target="_blank" rel="noreferrer" className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 text-white/35 hover:text-fuchsia-200"><ExternalLink className="h-4 w-4" /></a>}<button onClick={deleteProject} className="grid h-9 w-9 place-items-center rounded-xl border border-red-400/10 text-red-300/40 hover:bg-red-500/10 hover:text-red-300"><Trash2 className="h-4 w-4" /></button></div></div><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 xl:grid-cols-5">{STATUSES.map(status=><KanbanColumn key={status} status={status} tasks={selected.tasks.filter(t=>t.status===status)} onDrop={()=>moveDragged(status)} onDragStart={setDraggedTask} onOpen={setEditingTask} onDelete={deleteTask} onAdd={()=>addTask(status)} />)}</div></>}
    <div className="flex items-center gap-2 rounded-2xl border border-white/8 bg-white/[.018] px-4 py-3 text-[9px] leading-5 text-white/25"><Clock3 className="h-3.5 w-3.5 shrink-0 text-fuchsia-300/40" /> Seus projetos e tarefas continuam salvos na conta e sincronizados pelo sistema.</div>
  </div>{editingProject && selected && <ProjectEditor project={selected} onChange={updateProject} onClose={()=>setEditingProject(false)} />}{editingTask && <TaskModal task={editingTask} onSave={saveTask} onClose={()=>setEditingTask(null)} />}</Shell>;
}
