import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Waves, TrendingDown, Minus, TrendingUp, Brain, RotateCcw, Trash2, GlassWater, Eye, Compass, X, Play, Plus } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { applyXp, fetchHeroi } from "@/lib/api";
import { fireReward } from "@/components/fx/RewardBurst";

type WaveResult = "diminuiu" | "igual" | "aumentou";
type Trigger = "vontade_comer" | "vontade_beber" | "doce" | "comida_vista" | "fome" | "sede" | "tedio" | "ansiedade" | "habito" | "pensamento" | "outro";
type Step = "perceber" | "distanciar" | "investigar" | "observar" | "escolher";
type Wave = { id: string; date: string; initial: number; final: number; durationSeconds: number; result: WaveResult; trigger: Trigger; waterMl: number };
type Props = { embedded?: boolean };

const WAVE_STORAGE = (uid: string) => `ascensao:urge-surfing:${uid}`;
const WATER_STORAGE = (uid: string, day: string) => `ascensao:agua:${uid}:${day}`;
const WATER_ACTIONS_STORAGE = (uid: string, day: string) => `ascensao:agua-acoes:${uid}:${day}`;
const WATER_TARGET_STORAGE = (uid: string) => `ascensao:agua-meta:${uid}`;
const RESET_MARKER = (uid: string) => `ascensao:agua-reset:${uid}`;
const DEFAULT_WATER_TARGET = 4000;
const TRIGGERS: { id: Trigger; label: string; emoji: string }[] = [
  { id: "vontade_comer", label: "Vontade de Comer", emoji: "🍔" }, { id: "vontade_beber", label: "Vontade de Beber", emoji: "🥤" }, { id: "doce", label: "Vontade de Comer Doce", emoji: "🍫" },
  { id: "comida_vista", label: "Comida À Vista", emoji: "👀" }, { id: "fome", label: "Sensação de Fome", emoji: "🍽️" }, { id: "sede", label: "Sensação de Sede", emoji: "💧" },
  { id: "tedio", label: "Tédio", emoji: "😶" }, { id: "ansiedade", label: "Ansiedade", emoji: "😰" }, { id: "habito", label: "Hábito / Automático", emoji: "🔁" },
  { id: "pensamento", label: "Pensamento Intrusivo", emoji: "🧠" }, { id: "outro", label: "Outro", emoji: "❓" },
];
const STEPS: { id: Step; label: string; emoji: string }[] = [
  { id: "perceber", label: "Perceber", emoji: "👁️" }, { id: "distanciar", label: "Distanciar", emoji: "🧠" }, { id: "investigar", label: "Investigar", emoji: "🔎" }, { id: "observar", label: "Observar", emoji: "🌊" }, { id: "escolher", label: "Escolher", emoji: "🧭" },
];
const COPY: Record<Trigger, { noun: string; thought: string; question: string; guidance: string }> = {
  vontade_comer: { noun: "vontade de comer", thought: "Estou percebendo uma vontade de comer agora.", question: "O que minha mente está prometendo que comer vai resolver ou proporcionar?", guidance: "Observe a vontade de comer como uma experiência. Note fome, imagens, pensamentos e sensações sem transformá-los automaticamente em ação." },
  vontade_beber: { noun: "vontade de beber", thought: "Estou percebendo uma vontade de beber agora.", question: "Estou percebendo uma necessidade física, um hábito ou uma interpretação sobre o que preciso?", guidance: "Observe a sensação e os pensamentos associados. Perceber uma sensação não exige uma resposta automática." },
  doce: { noun: "vontade de comer doce", thought: "Estou percebendo uma vontade de comer doce agora.", question: "Que promessa esta vontade de doce está trazendo para minha mente?", guidance: "Observe o desejo por doce como uma onda de sensações, imagens e pensamentos. Perceba como ele muda." },
  comida_vista: { noun: "vontade ao ver comida", thought: "Estou percebendo uma reação ao ver comida.", question: "Que significado minha mente está dando ao estímulo de ver comida?", guidance: "Note o estímulo visual e a resposta automática. Ver comida não determina o que você fará em seguida." },
  fome: { noun: "sensação de fome", thought: "Estou percebendo uma sensação de fome neste momento.", question: "O que estou sentindo no corpo e que interpretação estou acrescentando?", guidance: "Observe as sensações corporais com curiosidade e diferencie percepção física de interpretação." },
  sede: { noun: "sensação de sede", thought: "Estou percebendo uma sensação de sede neste momento.", question: "O que estou percebendo fisicamente e que significado estou dando a isso?", guidance: "Observe a sensação corporal sem transformá-la imediatamente em conclusão. Percepção e interpretação são etapas diferentes." },
  tedio: { noun: "vontade provocada pelo tédio", thought: "Estou percebendo uma vontade que apareceu junto com o tédio.", question: "Estou buscando uma ação para mudar o estado de tédio?", guidance: "Observe o tédio e a vontade de preenchê-lo. Você pode permitir o desconforto enquanto decide." },
  ansiedade: { noun: "vontade associada à ansiedade", thought: "Estou percebendo uma vontade que apareceu junto com a ansiedade.", question: "Estou tentando eliminar a ansiedade rapidamente ou escolher uma resposta?", guidance: "Observe a ansiedade como uma experiência que pode variar. Você não precisa resolvê-la antes de escolher." },
  habito: { noun: "vontade automática de um hábito", thought: "Estou percebendo um impulso automático de repetir um hábito.", question: "O que costuma acontecer depois deste impulso e o que quero escolher desta vez?", guidance: "Observe a sequência gatilho → vontade → tendência de ação. Crie um espaço antes da resposta." },
  pensamento: { noun: "pensamento intrusivo", thought: "Estou percebendo um pensamento que apareceu na minha mente.", question: "Estou tratando este pensamento como fato ou apenas percebendo que ele apareceu?", guidance: "Pensamentos podem surgir automaticamente. Você pode examiná-los sem aceitá-los como fatos ou obedecê-los." },
  outro: { noun: "vontade que apareceu agora", thought: "Estou percebendo uma experiência interna que pede atenção.", question: "Que significado estou dando ao que estou percebendo agora?", guidance: "Primeiro perceba o evento; depois examine a interpretação; só então escolha uma resposta." },
};
function today() { return new Date().toLocaleDateString("en-CA"); }
function loadJson<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key) || "") as T; } catch { return fallback; } }
function loadWaves(uid: string) { return loadJson<Wave[]>(WAVE_STORAGE(uid), []); }
function saveWaves(uid: string, waves: Wave[]) { localStorage.setItem(WAVE_STORAGE(uid), JSON.stringify(waves.slice(0, 100))); }
function waterKey(uid: string) { return WATER_STORAGE(uid, today()); }
function actionKey(uid: string) { return WATER_ACTIONS_STORAGE(uid, today()); }
function loadWater(uid: string) { return Number(localStorage.getItem(waterKey(uid)) || 0); }
function loadActions(uid: string) { return loadJson<number[]>(actionKey(uid), []); }
function formatTime(s: number) { return `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}`; }
function untilTomorrow() { const n = new Date(); const next = new Date(n); next.setHours(24, 0, 0, 0); return Math.max(1000, next.getTime() - n.getTime()); }
function randomReward() { return Math.floor(Math.random() * 2) + 1; }

export default function UrgeSurfingCard({ embedded = false }: Props) {
  const { user } = useAuth(); const uid = user?.id;
  const [waves, setWaves] = useState<Wave[]>([]); const [water, setWater] = useState(0); const [waterTarget, setWaterTarget] = useState(DEFAULT_WATER_TARGET); const [waterActions, setWaterActions] = useState<number[]>([]);
  const [fasting, setFasting] = useState(false); const [open, setOpen] = useState(false); const [step, setStep] = useState<Step>("perceber"); const [trigger, setTrigger] = useState<Trigger>("vontade_comer"); const [initial, setInitial] = useState(5); const [finalIntensity, setFinalIntensity] = useState(5); const [choice, setChoice] = useState("");
  const [startedAt, setStartedAt] = useState<number | null>(null); const [seconds, setSeconds] = useState(0); const [targetSeconds, setTargetSeconds] = useState(300); const [saving, setSaving] = useState(false); const [customMl, setCustomMl] = useState(""); const [customOpen, setCustomOpen] = useState(false);

  const resetDailyWater = () => { if (!uid) return; setWater(0); setWaterActions([]); localStorage.setItem(waterKey(uid), "0"); localStorage.setItem(actionKey(uid), "[]"); };
  useEffect(() => {
    if (!uid) return;
    const load = async () => {
      const { data } = await supabase.from("users").select("agua_meta_ml, agua_reset_at").eq("id", uid).maybeSingle();
      const reset = data?.agua_reset_at ?? null;
      const seen = localStorage.getItem(RESET_MARKER(uid));
      if (reset && reset !== seen) {
        localStorage.removeItem(waterKey(uid)); localStorage.removeItem(actionKey(uid)); localStorage.setItem(RESET_MARKER(uid), reset); setWater(0); setWaterActions([]);
      } else {
        setWater(loadWater(uid)); setWaterActions(loadActions(uid));
      }
      const target = Number(data?.agua_meta_ml) || DEFAULT_WATER_TARGET;
      setWaterTarget(target);
      localStorage.setItem(WATER_TARGET_STORAGE(uid), String(target));
    };
    load();
    const sync = () => setFasting(Boolean(localStorage.getItem(`ascensao:jejum:${uid}:active`)));
    sync(); const timer = window.setInterval(sync, 1000); let midnight = 0;
    const schedule = () => { midnight = window.setTimeout(() => { resetDailyWater(); schedule(); }, untilTomorrow()); };
    schedule(); return () => { window.clearInterval(timer); window.clearTimeout(midnight); };
  }, [uid]);
  useEffect(() => { if (!startedAt) return; const tick = () => setSeconds(Math.max(0, Math.floor((Date.now() - startedAt) / 1000))); tick(); const t = window.setInterval(tick, 1000); return () => window.clearInterval(t); }, [startedAt]);

  const todayWaves = useMemo(() => waves.filter(w => w.date.slice(0, 10) === today()), [waves]);
  const decreased = todayWaves.filter(w => w.result === "diminuiu").length; const decreaseRate = todayWaves.length ? Math.round(decreased / todayWaves.length * 100) : 0;
  const progress = Math.min(100, waterTarget > 0 ? water / waterTarget * 100 : 0); const copy = COPY[trigger];
  const addWater = (ml: number) => { if (!uid || !Number.isFinite(ml) || ml <= 0) return; const n = Math.round(ml); const next = water + n; const actions = [...waterActions, n]; setWater(next); setWaterActions(actions); localStorage.setItem(waterKey(uid), String(next)); localStorage.setItem(actionKey(uid), JSON.stringify(actions.slice(-30))); };
  const addCustomWater = () => { const n = Number(customMl); if (!Number.isInteger(n) || n <= 0) return; addWater(n); setCustomMl(""); setCustomOpen(false); };
  const undoWater = () => { if (!uid || !waterActions.length) return; const last = waterActions.at(-1)!; const actions = waterActions.slice(0, -1); const next = Math.max(0, water - last); setWater(next); setWaterActions(actions); localStorage.setItem(waterKey(uid), String(next)); localStorage.setItem(actionKey(uid), JSON.stringify(actions)); };
  const startWave = () => { if (!fasting) return; setTrigger("vontade_comer"); setChoice(""); setStep("perceber"); setInitial(5); setFinalIntensity(5); setTargetSeconds(300); setSeconds(0); setStartedAt(null); setOpen(true); };
  const startTimer = () => { setSeconds(0); setStartedAt(Date.now()); };
  const closeWave = () => { if (saving) return; setStartedAt(null); setOpen(false); setStep("perceber"); };
  const finishWave = async (result: WaveResult) => {
    if (!uid || !startedAt || seconds < targetSeconds || saving) return; setSaving(true);
    try {
      const xp = randomReward(); const ouro = randomReward(); const atributoDelta = randomReward(); const current = await fetchHeroi(uid); if (!current) throw new Error("Herói não encontrado."); const nextXp = applyXp(current, xp);
      await supabase.from("users").update({ xp_atual: nextXp.xp_atual, nivel: nextXp.nivel, xp_proximo_nivel: nextXp.xp_proximo_nivel, ouro: current.ouro + ouro }).eq("id", uid);
      await supabase.from("transacoes_ouro").insert({ user_id: uid, valor: ouro, origem: "urge_surfing", descricao: "Urge Surfing" });
      const { data: attr } = await (supabase as any).from("hero_attributes").select("*").eq("user_id", uid).maybeSingle(); await (supabase as any).from("hero_attributes").upsert({ user_id: uid, consciencia: attr?.consciencia ?? 0, foco: attr?.foco ?? 0, autodominio: (attr?.autodominio ?? 0) + atributoDelta, coragem: attr?.coragem ?? 0, disciplina: attr?.disciplina ?? 0, gestao: attr?.gestao ?? 0, resiliencia: attr?.resiliencia ?? 0 });
      const wave: Wave = { id: crypto.randomUUID(), date: new Date().toISOString(), initial, final: finalIntensity, durationSeconds: seconds, result, trigger, waterMl: water }; const next = [wave, ...waves]; saveWaves(uid, next); setWaves(next); closeWave();
      fireReward(`+${xp} XP`, "#a855f7"); setTimeout(() => fireReward(`+${ouro} Ouro`, "#facc15"), 180); setTimeout(() => fireReward(`+${atributoDelta} Autodomínio`, "#22c55e"), 360);
    } finally { setSaving(false); }
  };

  const waterPanel = <div className="relative overflow-hidden rounded-xl border border-cyan-400/25 bg-gradient-to-br from-cyan-500/[.09] via-primary/[.04] to-background shadow-[0_0_24px_hsl(190_90%_50%/.06)]"><div className="relative p-3 sm:p-3.5 space-y-3">
    <div className="flex items-center gap-2.5"><div className="grid place-items-center w-9 h-9 rounded-lg bg-cyan-400/10 border border-cyan-400/25"><GlassWater className="w-4 h-4 text-cyan-300" /></div><div className="flex-1"><p className="text-[8px] uppercase tracking-[.28em] text-cyan-300">💧 RECURSO · HIDRATAÇÃO</p><p className="font-display text-sm tracking-wider">ÁGUA DE HOJE</p></div><span className="font-display text-sm text-cyan-300">{Math.round(progress)}%</span></div>
    <div className="flex items-end justify-between"><div><span className="font-display text-2xl sm:text-3xl text-cyan-200">{water.toLocaleString("pt-BR")}</span><span className="ml-1 text-xs text-muted-foreground">ml</span></div><span className="text-[9px] text-muted-foreground">Meta {waterTarget.toLocaleString("pt-BR")} ml</span></div>
    <div className="h-2 rounded-full bg-black/25 border border-white/5 overflow-hidden"><motion.div className="h-full rounded-full bg-gradient-to-r from-cyan-500 to-cyan-300" animate={{ width: `${progress}%` }} /></div>
    <div className="rounded-lg border border-cyan-400/15 bg-cyan-400/[.035] p-2.5"><p className="text-[9px] uppercase tracking-[.2em] text-cyan-300 mb-2">Adicionar água</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-1.5"><button onClick={() => addWater(100)} className="rounded-lg border border-cyan-400/20 bg-cyan-400/[.06] hover:bg-cyan-400/[.12] py-2 text-[10px] font-semibold text-cyan-200 transition">+100 ml</button><button onClick={() => addWater(200)} className="rounded-lg border border-cyan-400/20 bg-cyan-400/[.06] hover:bg-cyan-400/[.12] py-2 text-[10px] font-semibold text-cyan-200 transition">+200 ml</button><button onClick={() => addWater(400)} className="rounded-lg border border-cyan-400/20 bg-cyan-400/[.06] hover:bg-cyan-400/[.12] py-2 text-[10px] font-semibold text-cyan-200 transition">+400 ml</button><button onClick={() => setCustomOpen(v => !v)} className={`rounded-lg border py-2 text-[10px] font-semibold transition ${customOpen ? "border-primary bg-primary/10 text-primary" : "border-cyan-400/20 bg-cyan-400/[.06] text-cyan-200 hover:bg-cyan-400/[.12]"}`}>Outro</button></div>{customOpen && <div className="flex gap-2 mt-2"><input type="number" min="1" step="1" inputMode="numeric" value={customMl} onChange={e => setCustomMl(e.target.value)} onKeyDown={e => { if (e.key === "Enter") addCustomWater(); }} placeholder="Quantidade em ml" className="min-w-0 flex-1 bg-secondary border border-border rounded-md px-3 py-2 text-sm" /><button onClick={addCustomWater} disabled={!customMl || Number(customMl) <= 0} className="btn-pixel px-3 rounded-md text-xs flex items-center gap-1 disabled:opacity-40"><Plus className="w-3.5 h-3.5" /> Adicionar</button></div>}</div>
    <div className="flex items-center justify-between gap-2"><button onClick={undoWater} disabled={!waterActions.length} className="flex items-center gap-1.5 text-[9px] text-muted-foreground hover:text-cyan-200 disabled:opacity-30"><RotateCcw className="w-3 h-3" /> Desfazer{waterActions.length ? ` · -${waterActions.at(-1)} ml` : ""}</button><button onClick={resetDailyWater} disabled={!water} className="flex items-center gap-1.5 text-[9px] text-muted-foreground hover:text-destructive disabled:opacity-30"><Trash2 className="w-3 h-3" /> Zerar Hoje</button></div>
  </div></div>;

  const waveStats = fasting && <div className="mt-2 grid grid-cols-3 gap-1.5 text-center"><div className="rounded-lg border border-primary/15 bg-primary/[.035] py-2"><p className="text-[8px] text-muted-foreground">🌊 ONDAS HOJE</p><p className="font-display text-sm text-primary">{todayWaves.length}</p></div><div className="rounded-lg border border-primary/15 bg-primary/[.035] py-2"><p className="text-[8px] text-muted-foreground">📉 DIMINUÍRAM</p><p className="font-display text-sm text-primary">{decreaseRate}%</p></div><div className="rounded-lg border border-primary/15 bg-primary/[.035] py-2"><p className="text-[8px] text-muted-foreground">🏆 TOTAL</p><p className="font-display text-sm text-primary">{waves.length}</p></div></div>;

  const modal = <AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[95] bg-background/90 backdrop-blur-md flex items-center justify-center p-4"><motion.div initial={{ y: 24, scale: .97 }} animate={{ y: 0, scale: 1 }} className="relative w-full max-w-lg max-h-[92vh] overflow-y-auto rounded-2xl border border-primary/30 bg-card/95"><button onClick={closeWave} disabled={saving} className="absolute right-3 top-3 z-10 rounded-full p-2 text-muted-foreground hover:text-foreground"><X className="w-4 h-4" /></button><div className="p-5 sm:p-6 space-y-5">
    <div className="text-center"><motion.div animate={{ y: [0, -4, 0] }} transition={{ duration: 2, repeat: Infinity }} className="mx-auto grid place-items-center w-14 h-14 rounded-2xl border border-primary/30 bg-primary/10"><Waves className="w-7 h-7 text-primary" /></motion.div><p className="text-[9px] uppercase tracking-[.32em] text-primary mt-3">🌊 PROTOCOLO DE ONDA</p><h2 className="font-display text-2xl tracking-widest mt-1">VONTADE ≠ COMANDO</h2><p className="text-xs text-muted-foreground mt-2">Observe a experiência. Crie distância. Escolha a resposta.</p></div>
    <div className="flex items-center gap-1.5">{STEPS.map((s, i) => <div key={s.id} className="flex-1"><div className={`h-1 rounded-full ${STEPS.findIndex(x => x.id === step) >= i ? "bg-primary" : "bg-white/10"}`} /><p className={`mt-1 text-center text-[7px] uppercase tracking-wider ${step === s.id ? "text-primary" : "text-muted-foreground"}`}>{s.emoji} {s.label}</p></div>)}</div>
    {step === "perceber" && <div className="space-y-4"><div className="rounded-xl border border-primary/20 bg-primary/[.04] p-4 text-center"><p className="text-[9px] uppercase tracking-[.25em] text-primary">👁️ PERCEBA</p><p className="font-display text-lg mt-2">Você percebe uma {copy.noun}.</p><p className="text-xs text-muted-foreground mt-2">{copy.thought}</p></div><p className="text-[10px] uppercase tracking-[.2em] text-muted-foreground">O que apareceu?</p><div className="grid grid-cols-2 gap-2">{TRIGGERS.map(t => <button key={t.id} onClick={() => setTrigger(t.id)} className={`rounded-xl border p-3 text-left ${trigger === t.id ? "border-primary bg-primary/10 text-primary" : "border-border"}`}><span className="text-lg">{t.emoji}</span><span className="ml-2 text-[10px]">{t.label}</span></button>)}</div><button onClick={() => setStep("distanciar")} className="w-full rounded-xl bg-primary py-3 text-xs font-bold text-primary-foreground">PERCEBI → CONTINUAR</button></div>}
    {step === "distanciar" && <div className="space-y-4"><div className="rounded-xl border border-primary/20 bg-primary/[.04] p-4"><div className="flex items-center gap-2 text-primary"><Brain className="w-4 h-4" /><span className="text-[9px] uppercase tracking-[.25em]">🧠 DISTANCIE</span></div><p className="font-display text-lg mt-3">Você percebe a {copy.noun}.</p><p className="font-display text-xl text-primary mt-1">Você não precisa obedecer a ela.</p><p className="text-xs text-muted-foreground mt-3">{copy.guidance}</p></div><button onClick={() => setStep("investigar")} className="w-full rounded-xl bg-primary py-3 text-xs font-bold text-primary-foreground">CRIEI DISTÂNCIA → CONTINUAR</button></div>}
    {step === "investigar" && <div className="space-y-4"><div className="rounded-xl border border-primary/20 bg-primary/[.04] p-4"><div className="flex items-center gap-2 text-primary"><Compass className="w-4 h-4" /><span className="text-[9px] uppercase tracking-[.25em]">🔎 INVESTIGUE</span></div><p className="font-display text-lg mt-3">{copy.question}</p><p className="text-xs text-muted-foreground mt-2">Observe a interpretação que apareceu primeiro.</p></div><div className="space-y-2">{["É uma necessidade urgente.", "É um pensamento ou impulso que apareceu.", "É uma sensação que posso observar.", "Não tenho certeza ainda."].map(text => <button key={text} onClick={() => setChoice(text)} className={`w-full rounded-xl border p-3 text-left text-xs ${choice === text ? "border-primary bg-primary/10 text-primary" : "border-border"}`}>{text}</button>)}</div><button disabled={!choice} onClick={() => setStep("observar")} className="w-full rounded-xl bg-primary py-3 text-xs font-bold text-primary-foreground disabled:opacity-40">OBSERVEI → IR PARA A ONDA</button></div>}
    {step === "observar" && <div className="space-y-5"><div className="text-center"><p className="text-[9px] uppercase tracking-[.25em] text-primary">🌊 OBSERVE A ONDA</p><p className="font-display text-5xl text-primary tracking-widest mt-2">{formatTime(seconds)}</p><p className="text-xs text-muted-foreground mt-1">{!startedAt ? "Escolha um período para praticar" : seconds < targetSeconds ? `Observe por mais ${formatTime(targetSeconds - seconds)}` : "Tempo concluído — agora você pode escolher."}</p></div><div className="rounded-2xl border border-primary/20 bg-primary/[.035] p-4"><p className="text-[9px] uppercase tracking-[.22em] text-primary">🧭 GUIA DURANTE A PRÁTICA</p><p className="text-[10px] text-muted-foreground mt-2">1. Note onde a vontade aparece no corpo.</p><p className="text-[10px] text-muted-foreground">2. Observe pensamentos e imagens sem discutir.</p><p className="text-[10px] text-muted-foreground">3. Perceba se a intensidade muda sozinha.</p><p className="text-[10px] text-muted-foreground">4. Reconheça: “é uma vontade, não uma ordem”.</p><p className="text-[10px] text-muted-foreground">5. Retorne à respiração e às sensações presentes.</p></div>{!startedAt ? <><div className="grid grid-cols-3 gap-2">{[180,300,600].map(s => <button key={s} onClick={() => setTargetSeconds(s)} className={`rounded-xl border py-3 text-xs ${targetSeconds === s ? "border-primary bg-primary/10 text-primary" : "border-border"}`}>{s / 60} min</button>)}</div><button onClick={startTimer} className="w-full rounded-xl bg-primary py-3 text-xs font-bold text-primary-foreground flex items-center justify-center gap-2"><Play className="w-4 h-4" /> INICIAR {targetSeconds / 60} MIN</button></> : <>{seconds >= targetSeconds ? <button onClick={() => setStep("escolher")} className="w-full rounded-xl bg-primary py-3 text-xs font-bold text-primary-foreground">PRÁTICA CONCLUÍDA → ESCOLHER</button> : <p className="text-center text-[9px] text-muted-foreground">Respire naturalmente. Observe sem lutar e sem obedecer automaticamente.</p>}</>}</div>}
    {step === "escolher" && <div className="space-y-4"><div className="rounded-xl border border-primary/20 bg-primary/[.04] p-4 text-center"><p className="text-[9px] uppercase tracking-[.25em] text-primary">🧭 ESCOLHA</p><p className="font-display text-xl mt-2">O que mudou?</p><p className="text-xs text-muted-foreground mt-1">A meta não era eliminar a vontade. Era criar espaço para escolher.</p></div><input type="range" min="1" max="10" value={finalIntensity} onChange={e => setFinalIntensity(Number(e.target.value))} className="w-full accent-primary" /><div className="grid grid-cols-3 gap-2"><button disabled={saving} onClick={() => finishWave("diminuiu")} className="rounded-xl border border-emerald-400/30 p-3 text-xs text-emerald-300"><TrendingDown className="w-5 h-5 mx-auto mb-1" />Diminuiu</button><button disabled={saving} onClick={() => finishWave("igual")} className="rounded-xl border border-border p-3 text-xs"><Minus className="w-5 h-5 mx-auto mb-1" />Igual</button><button disabled={saving} onClick={() => finishWave("aumentou")} className="rounded-xl border border-amber-400/30 p-3 text-xs text-amber-300"><TrendingUp className="w-5 h-5 mx-auto mb-1" />Aumentou</button></div></div>}
    <div className="rounded-xl border border-white/5 bg-white/[.02] p-3 flex items-center gap-3"><Eye className="w-4 h-4 text-primary" /><p className="text-[9px] text-muted-foreground">Notar uma experiência interna, observar sua interpretação e criar um intervalo antes de agir.</p></div>
  </div></motion.div></motion.div>}</AnimatePresence>;
  if (embedded) return <><button onClick={startWave} disabled={!fasting} className="w-full rounded-lg border border-primary/25 bg-primary/[.045] hover:bg-primary/[.09] py-2.5 px-3 transition disabled:opacity-40"><div className="flex items-center justify-center gap-2"><Waves className="w-4 h-4 text-primary" /><span className="text-[10px] font-semibold uppercase tracking-[.16em] text-primary">Estou Com Vontade</span><span>🌊</span></div></button>{waveStats}{modal}</>;
  return <>{waterPanel}{modal}</>;
}
